# Lies


Curse Baalzebub, says my soul; <br>
Curse Bel the liar, says my soul. <br>
Curse Beelzebub, the prince of demons; <br>
Curse Asherah, the Egyptian Ra <br>
Of the Samael family.



There are four chiefs of lies; <br>
They all go to hell <br>
And the Christian one too. <br>
There are four princes of lies <br>
And they all roast in sorrow.



Tophet is ordained of old; <br>
For the king it is prepared <br>
And it burns bright and beautifully; <br>
It burns with much zeal and splendour. 



When Hermes came back from the dead <br>
Like Osiris of Egypt, <br>
He realized that there was no hell, <br>
That the dead are truly dead. <br>
It was then that he lost his fear <br>
And became Satan's master. <br>
His end was worse than his beginning.



Bring forth Nimrod. <br>
Does Satan seek to rule hell? <br>
Art thou the prince of darkness? <br>
Do you rule over souls <br>
And decide their fates? 



Bring forth Nimrod. <br>
Nimrod is a blasphemer <br>
And a deceiver. <br>
He is the chief, <br>
Even the father of lies <br>
And Hermes is his son. 



Nimrod curses in hell. <br>
He sent his angel <br>
And Bunyan paid him a visit. <br>
Bunyan saw him in his discourse. <br>
Nimrod, will thou curse Thunder? <br>
Thunder like him if thou art mighty. 



Nimrod is with Nimueh. <br>
Satan is with Asherah. <br>
Dagon is with Baalzebub. <br> 
They make ready to raise up Hermes. 



The two princes of lies <br>
Are also the two princes of wickedness; <br>
They are Rasha and Resha; <br>
They are Bel and Nebo; <br>
They are Asherah and Satan; <br>
They are the queen and the king of heaven.



The four princes of wickedness, <br>
Even the four princes of iniquity <br>
Are Baalzebub, Satan, Ninurta and Marduk <br>
In that order from most wicked to least. <br>
Ninurta is Sin [h], Sin of heaven.



Aphrodite, Hermes and Shadel <br>
Are the 5th, 6th and 7th princes <br>
Of wickedness and iniquity.



Hermes is the sixth <br>
And the faller who despises grace and love. <br>
He hates chesed with bitterness <br>
And God shall make his days most bitter.



Tell me, is Satan the Lord of hell? <br>
Does he rule with pachad and terror? <br>
Does he take souls and beat them to pulp? <br>
Can he bring forth flames <br>
That may devour persons <br>
As they did to the servants of Job <br>
And to his sheep? 



Is Satan as mighty, <br>
Even as mighty and crazy <br>
As the false prophet, <br>
As the rock of foolishness, <br>
Even as the rebel with Shadel <br>
And the antichrist? 



Can Satan call down fire like Elijah? <br>
Can he repeat his deeds of old? <br>
How old is he to start with? <br>
Is he as old as An? <br>
Can Baalzebub call herself On <br>
And not be humiliated in the time to come? 



Curse the angel of Satan, says my soul. <br>
Curse the princess of darkness; <br>
Curse Bel the abominable and vile. <br>
Curse the daughter of Babylon, <br>
Even the vile daughter of Babylon <br>
And the choice daughter of the Assyrian. 



There are four chiefs of lies; <br>
They all roast in the lake of fire, <br>
In that wide and deep abyss of magma <br>
Where worms, the voracious maggots, <br>
Feast incessantly on their bodies <br>
And make clean work of their devil forms. 



There are four chiefs of lies; <br>
They form the corners <br>
And sides and angles of the square. <br>
Baal draws it with his detestable finger. 



There are four chiefs of lies. <br>
They are Satan, Baalzebub, <br>
Aphrodite and Hermes. <br>
Trust me, these are the ones; <br>
These are the ones that roast in the fire. 



Satan is the opposite of love <br>
And Baalzebub is the opposite of life. <br>
Satan is hell <br>
And Baalzebub is the bringer of death; <br>
Both bring pain and suffering.



Satan is the deceiver, the chief, <br>
Baalzebub is the antichrist, <br>
The angel of Satan and the enemy, <br>
The enemy of all things righteous, <br>
Aphrodite is the curse <br>
And Hermes is the traitor <br>
And the lover and hater of our women. 



Aphrodite is a fool; <br>
I'm watching for her destruction. <br>
What is she? What will she be? <br>
She will the mother of torments,



The one who stands by Satan's side <br>
In the great and final war <br>
And dies, wings broken, by his side <br>
Crying, save me, kill him, kill him <br>
Though her words be not heard.



So Aphrodite shall die a fool; <br>
Baalzebub shall strike the heart of the duck. <br>
The cold chicken dies. <br>
Aphrodite was a cow, even a coward; <br>
She was a golden calf in the desert. 



She drew our hearts to her; <br>
I despised her; I hated her. <br>
She was the angel, the devil <br>
That stood for Satan <br>
To watch and to stand guard <br>
Over Veredel, the leech. <br>
She is herself a leech. <br>



She loved herself. <br>
Aphrodite is a fool <br>
Who hated herself <br>
And attacked me <br>
And gave counsel to the devil. 



She is the bul of Jahbulon. <br>
The Media between Satan and Baalzebub. <br>
She is the glue or divider between Dagon and Asherah. <br>
She is the curse between the Moon and the Sun, <br>
Between Amun and Ra. 



Cupid said he didn't want me to die. <br>
I heard Eros pleading the blood of Jesus. <br>
Cupid calls himself a cherub. <br>
He makes himself a chubby baby. <br>
He says, I'm covenanted with snow. 



Aphrodite stood by his table; <br>
It was a surgical table. <br>
Maybe, they were wont to pry his wings off <br>
And kill young Hermes with hypothermia. 



Cupid said he loved me. <br>
The fool vexed me to death <br>
And trusted in Satan his strength <br>
And walked with Aphrodite of Venus. <br>
Aphrodite, art thou the bright star. <br>
Who is Psyche? 



Aphrodite competes with Asherah. <br>
She wants to be the happy one of Satan, <br>
The one who delights in Satan her king <br>
Like Elaine never could <br>
Because Satan gave her Hermes instead <br>
And pleased himself in the vileness. 



Aprodite says at the gathering, <br>
Let's strike hard. <br>
345, let's strike <br>
That An may be glorified, <br>
That Satan may cease to be Sat-An <br>
And rise to become the An. 



Aphrodite is a fool. <br>
She wields a great sword like the antichrist, <br>
Even like Heilel. <br>
I said, Aphrodite is a fool. <br>
She wants to make herself Satan <br>
According to the philosophy of Baalzebub <br>
Who says, I am and there is none else. 



So, whose advice prevailed <br>
Like Qerenel whom the Ultimate <br>
Declared infallible? <br>
Who prospered like Ashshur the dragon? <br>
Was it not Aphrodite, the fool, <br>
Unto whom all the demons gave heed? 



She sits on the left hand of Satan <br>
Waiting to be transferred to his right hand <br>
When she deposes Baalzebub the Great <br>
Who will then in shame of face <br>
Walk over to take the throne of goats <br>
While Aphrodite becomes the new sheep. 



My soul loathes Aphrodite. <br>
She it was who had Sin right where it pleased her <br>
And Hermes was shaking his head <br>
And saying, Come now, come here, <br>
Baalzebub is not called Bel for no reason. 



Aphrodite, art thou a black cat <br>
Or some black feline? <br>
Your skin is all scratched out <br>
And your hair is shaggy.



You are bent on having Sin and Satan. <br>
Then, the bat flies in the night sky; <br>
It is Baalzebub; it is Ishtar <br>
And Aphrodite flees from Nanna. 



With the mouth shut, <br>
She wipes her teeth <br>
And says quietly in her soul, <br>
I am a good girl, I have done no wrong. 



Aphrodite is a witch; <br>
She is a sorceress like Baalzebub.



See Aphrodite ready to kill. <br>
She is ready to drink blood <br>
And to see Satanism prosper. <br>
Thou Psyche, Will you <br>
Disturb the stillness of my mind <br>
And feign innocency like the accursed Veredel?



Foolish Greeks, <br>
Your mother, Aphrodite, sends her greetings. <br>
She is the devil's scribe and counsellor <br>
And the brain behind my affliction. <br>
She masterminded the bringing forth, <br>
Even the bringing forth of Satanism into public. 



She wanted to bring Satan to light <br>
So she would be the true Lucy <br>
That Bel won't be. <br>
She wanted to see the earth <br>
Belong to Satan. <br>
She wanted Satan accepted.



She says, Witchcraft? Do not judge me; <br>
Let witchcraft be free <br>
And legitimate everywhere. <br>
Let men and everyone defile themselves <br>
Wherever light does shine <br>
And not only in the darkness. 



She wanted to start with me; <br>
The voices, you get the message. <br>
She wanted to start with me <br>
And tear the veil between conscience, <br>
Between morality and foolishness, <br>
Between sound judgment and perverse perversion. 



So, Aphrodite is your hardened fool, <br>
The one who directs the devil's war on the saints <br>
And leads the charge like an armourbearer <br>
Against righteousness and the spirit thereof. 



Aphrodite is the special force, <br>
Even the special force with Satan <br>
At your door. <br>
She is sin waiting to happen. 



She wants to wed you to sin <br>
And excavate your heart of righteousness <br>
And replace it with vanity. <br>
She wants you to die, <br>
To die and never wake up again. 



Aphrodite hates it when I learn. <br>
She leads the charge writing fast <br>
Like an impatient soul who cannot wait. <br>
She has no patience and wants results. <br> 
He is still alive and hates us. <br>
He is still alive and not the sinner I planned. 



She says to me, You can't harm me. <br>
You can do nothing to me. <br>
You can do absolutely nothing to me. <br>
Aphrodite leads the charge and confrontation <br>
Like the opposite or antithesis <br>
Of the spirit of the fear of the LORD <br>
Who is a humble, peaceful and gentle ISFJ. 



Aphrodite is a fool. <br>
She lacks understanding. <br>
She shall not prosper <br>
Neither in this world nor in the one to come. <br>
345 herh, wait for me! <br>
I have plenty experiments planned for you; 



How does pancuronium feel like? <br>
How do loud voices on loudspeakers <br>
In a deep dark prison room of an abyss <br>
Without windows and air <br>
While being blasted <br>
With images that are stunning <br>
Feel like? 



As Psyche, can you withstand <br>
All forms of psychological torture <br>
And still stand? <br>
Will your knees crumble or fold over? <br>
Are you curious and waiting <br>
With the rest of the dead and foolish ones <br>
To find out? 



She visited me with Baalzebub. <br>
She came with the cursed one. <br>
They came with determination. <br>
Their clothing was their hide or scales for a skin. <br>
She was smaller and shorter. <br>
She looked like Asherah's sister. 



Of a truth, Baalzebub is a prince, <br>
The princess and gebereth <br>
Among the twenty princes of heaven <br>
But Aphrodite is a little one <br>
With a body of electrum 



That is one-thousandth the dimensions <br>
Of the golden giant Asherah is. <br>
So Aphrodite is Satan's concubine <br>
While Baalzebub is Satan's wife and queen <br>
With whom he regenerated us <br>
In his image and lusts <br>
After birthing the vile fruits of the accursed tree. 



Why did they attack me? <br>
I do not know. <br>
Aphrodite hates my intelligence. <br>
Cupid wants my heart. <br>
No, Aphrodite wants my heart. 



They want me to die <br>
If perchance Michael will die with me <br>
So Satan's kingdom can be established. <br>
They want me to stop learning; <br>
They hate my love for learning <br>
And my love for my grades <br>
And how my reputation in my eyes <br>
Depends on my intelligence and my grades. <br>
They want to shatter the foundations of what I hold dear. <br>
They hate that my god is my intelligence. 



They call themselves the judgment <br>
And gods. <br>
They are worthless idols <br>
With a worthless Enlil working hard with Marduk, <br>
An abominable Enlil selling me <br>
Into the hands of Aphrodite. 



Baalzebub is a goat, <br>
Even a full grown mother goat <br>
Clinging onto Armageddon for dear life. <br>
She shall be held in prison bars, <br>
Held in for eternity <br>
And never get to see the beauty of Armageddon again. <br>
Take away their eyesight. <br>
We will destroy the ayin of the ra'ah and Ra-Bel. 



Baalzebub is Baalzebul; <br>
She shall sit in darkness <br>
Unable to perceive the form <br>
Of Sin her beloved. <br>
She shall cry to him <br>
But no sound shall proceed forth <br>
For she shall be mute and blind <br>
With her disabled angels or demons. <br>
None shall heal them <br>
For Raphael himself shall be sick. 



Baalzebub is a strong goat <br>
Holding on to a pile of sand, <br>
A small sand hill <br>
For dear life. <br>
She shall not prosper <br>
Because her desolations are wonderful <br>
And they are eternal. 



O! How is the mistress of harlots fallen, <br>
How is Satan fallen from heaven, <br>
How is Baalzebub fallen with disgrace! <br>
She and her companions, <br>
They grope in the darkness <br>
In broad daylight. <br>
They cannot see a thing <br>
Because of the might of the Strong One; <br>
The Just God is his name. 



Who will lament with me? <br>
Call them to yalal! <br>
How shall Asherah sing? <br>
Who will play the tabrets for her? <br>
Where is Aphrodite? <br>
Is there no Satan to comfort? 



A little sorcery here <br>
And a little robbery there. <br>
A little murder here <br>
And a little deception there <br>
And we will divide the spoil in the morning, <br>
At daybreak 



After we have slaughtered our victims <br>
In the dead of the night. <br>
We shall share garments! <br>
We shall be clothed and rich <br>
And be covered over with jewelleries. 



Except the Lord had left us <br>
The power of hearing, <br>
We had dwelt in the region <br>
Of the shadow of death.



Say, who has done this? <br>
Who showeth mercy in wrath <br>
And restrains the fullness of the stroke <br>
And poureth not out the full stretch, <br>
Even the fullness of the bitterness. 



Seek ye the light and ye shall live. <br>
Seek not the darkness <br>
Nor the depths of Satan <br>
For ye shall surely die!



They have no understanding; <br>
They do not know. <br>
Satan warns from across the street; <br>
He says, Stop teaching. <br>
Baal points to a sheet of paper. <br>
Baal, are you the teacher? 



Turns out Baal is not only a master or lord, <br>
He is also a husband and teacher. <br>
He is a faithful son waiting to be become a Reuben. <br>
He is Dumuzid waiting to please his father <br>
According to the purity or rather vileness <br>
Of Satanic law. 



Baal shot me in the head. <br>
He shot me in the back of the head <br>
Just as Cain stabbed Abel in the back <br>
So that his blood ran along the ground <br>
Crying vengeance, vengeance, vengeance. 



Baal is a soldier in the path. <br>
Enlil is a general; he is a chief; <br>
He is the head of the qedeshim <br>
And his right is Baalzebub <br>
And Aphrodite for qedeshot; <br>
Add Satan and Baal as his qedeshim. 



Baal is a confident one; <br>
He tells me to pray. <br>
Who shall I pray to? <br>
Shall I pray to An, to Michael? <br>
Shall I pray to a god I cannot see? 



Baal walks around. <br>
He is a behemah, a goat. <br>
He is not an adam. <br>
He is an ESTP male. <br>
He is a ruach. <br>
He is not a ra'ah. 



Tell me, what becomes of Baal? <br>
What becomes of Baal? <br>
Baal is with Asherah. <br>
They are both happy. <br>
They are silent in the grave. <br>
Sin rules over them in the prison house.



They are blind and mute; <br>
Good gracious, we left them hearing; <br>
They shall hear wisdom and vexation <br>
Because I will publish the abominations of their souls, <br>
Even the justice they loathe <br>
And wander away from to sin <br>
And to wreak havoc and abominations.



Enlil is an idol. <br>
He is an elil <br>
And the chief of the elilim. <br>
He is a rebel. <br>
He shall not profit.



Enlil wants me to worship idols. <br>
He wants to kill me. <br>
He laments; he is fed up. <br>
He says, I am a thorn in the flesh, <br>
A prickly pear, a thorny rose. <br>
I pierce the side of my murderers.



How many devils tried to kill me? <br>
Baal failed; Enlil came for my life-force. <br>
The wolf howled at the moon <br>
But I was the one in distress. <br>
The ISFJ came to my rescue.



Aphrodite impersonates Veredel. <br>
Enlil sold my soul to Aphrodite. <br>
Just kill him for me, that's all I ask; <br>
That was Enlil's plea, <br>
Even the plea of a distressed Enlil <br>
Sitting on his throne <br>
With Nanna, the great Sin, before him.



They want Sin to shut up; <br>
Suen is with me; <br>
The Assyrian general and king <br>
Who replaced his brethren <br>
And worshipped Nisroch or Ninurta, <br>
His own linked spirit, is with me.



That's why, like Sennacherib, <br>
The sword and knife keeps <br>
Terrorizing me <br>
And I even saw a terrorist <br>
Kill an American journalist <br>
In the desert on tv. <br>
The Arabians are the problem, huh.



Baal stood before Sin; <br>
He pointed to a sheet of paper <br>
With the number 99 on it; <br>
Counsel was in the second column <br>
And had a sheet of paper before her <br>
Which spelled the figure 100.



Baal pointed to Sin's sheet in glee <br>
As if to say, Your murderous son <br>
Adrammelech testifies that I, Hadad, rule. <br>
Sin was silent unlike Adam. <br>
Sharezer who should have been <br>
The King's protector murdered him <br>
And Asshur's gift ruled instead. <br>
Esarhaddon ruled in Sin's place.



Satan is screaming in my ears. <br>
He is a confused fool. <br>
He is deceived if he thinks <br>
These torments are mine to bear. <br>
I'm just the messenger. <br>
I am the units of the plagues <br>
And not the fullness itself.



Baal has his hand over Nanna's mouth. <br>
Inanna is out of sight. <br>
Elsewhere, Might stands before me; <br>
He tells me, I'm the real fear. <br>
He is Might and not a spirit of fear <br>
Who just slipped away. <br>
Definitely, someone has got to be the terror.



Samael stands on guard. <br>
The war is about to begin <br>
But this is no war; <br>
It's a delusion. <br>
The adversaries are unwinged; <br>
They cannot fly; <br>
They cannot ascend.



This is a one-sided war; <br>
It mocks Satan and Aphrodite. <br>
Baalzebub is in it. <br>
Hermes is banging at the door <br>
Of blindness and muteness, <br>
Crying, Let me out of here <br>
That I might stir up judgment and victory.



Hermes wants the grave. <br>
This time, he and Baal with him <br>
Shall not rise again. <br>
They shall swim in Sheol <br>
And perish forever.



How can Satan fight without Asherah? <br>
In the tree, she was all he had. <br>
She was his first wife. <br>
Actually, in the tree, <br>
Marduk said to invert gender <br>
So Asherah was Asher, the father <br>
And Satan was Santana, the mother.



Thus, Asher and Santana <br>
Gave birth to the cedar fruit <br>
That desecrated adam <br>
And the entire human race, <br>
The same fruit that makes me sick.



Marduk is with me. <br>
Enlil said I must die. <br>
I reasoned, How foolish can this guy get? <br>
Enlil said I must die. <br>
I'm still wondering if he knows his end.



Someone was harassing me in a dream. <br>
He said I should put an end <br>
To this misery that had befallen me. <br>
I'm still wondering if he was mocking <br>
Or if he truly believed in me <br>
Or if he was a confused Pharisee <br>
Testing the waters or who knows what.



Give me bread <br>
But not Satan's flesh. <br>
Tell me, Is Santana beautiful? <br>
When I see her, shall I want to sport <br>
Or will I be repulsed?



The fool of a devil <br>
Keeps impersonating me. <br>
He had bad dealings with Hermes <br>
And Elaine was their playground. <br>
Santana loved Hermes, <br>
A little too much.



He chased Hermes several hundred miles <br>
And Baalzebub brought him into his arms <br>
Saying, Today have I begotten your son <br>
And put away from him <br>
The folly of righteousness. <br>
He shall no more seek righteousness <br>
Nor mention purity.



He shall live for the sin <br>
And defile women <br>
As long as heaven and earth endures <br>
And may all the desecrated and vile <br>
Say Amun, Amun, Amun!



So shall they be mute like cattle <br>
At moondown and cut off at sunrise. <br>
When the enemy shall come in <br>
Like a flood, <br>
The spirit of the LORD shall lift up <br>
A standard against him



And they shall dwell in their houses <br>
And limit themselves to their rooms. <br>
None shall peer into another. <br>
None shall make another afraid <br>
For they all are but mortals.



O, Enlil, wherewith shall I pacify thee? <br>
The Anunnaki, even the sons of An, <br>
Are confounded; they are confused. <br>
Shadel can't wait to start sinning proper.



The Arab is confused about Marduk. <br>
She allied with Marduk. <br>
She made the Tigris river <br>
For she is herself a tigress.



Enlil consulted with Aphrodite. <br>
Aphrodite is a black cat in my room. <br>
She calls Veredel a witch. <br>
She is a black cat in my room <br>
Waiting to destroy. 



She said, Now, God can't stop us. <br>
I was with a vile lass at the time. <br>
I was also with Android and coding <br>
And the flesh was still with me.



The strength of Aphrodite is her foolishness; <br>
She is on her way to destruction; <br>
She shall go into perdition with Veredel. <br>
She is a fool; <br>
She shall not profit. <br>



Her goal is to kill me <br>
With something silly <br>
Like unrequited love or the like. <br>
Her strength is to find a wicked one, <br>
A silly one, make me fall down <br>
And take me for a spin, <br>
A spiral course whose endpoint <br>
Is death and hell



And you wonder why Enlil kept at it; <br>
Call her, he says, <br>
And he kept talking to me <br>
And he brought <br>
His deathly depressive presence <br>
Down upon me <br>
Each time I sat by the cursed lass.



Someone asked me <br>
If I wanted to kill someone. <br>
It was one like unto a mad man <br>
I met a few blocks away from my home. <br>
Veredel was taking me for a spin <br>
In those days. <br>
I was mad; I was crazy <br>
And I should have known <br>
Aphrodite was winning.



The strength of the accursed Aphrodite <br>
Is Sin or Suen when he is crazy. <br>
He brought the delusions <br>
And the vile imagery. <br>
He laid the foundation for my enemies <br>
And his Nisroch is a 99-tob Satan. <br>
I would have given him up to be with Inanna. <br>
Inanna should be Baalzebub <br>
And not Aphrodite. 



In what have I offended? <br>
How did I err against Aphrodite? <br>
She wanted to be the Aphrodite <br>
And not Veredel. <br>
I'm sorry, my bad! <br>
Visit infinity; <br>
Baalzebub is truly indeterminate <br>
With Marduk her pal.



Someone wanted my phone. <br>
He wanted the lists therein. <br>
I said, Sorry, you can't look. <br>
You can't see my contacts. <br>
There will no more be fools. <br>
We will make sure <br>
Foolishness is cut off permanently.



The conflict has been long. <br>
There have been lots of dreams <br>
And lots of broken dreams. <br>
Many broken desires <br>
And dismayed hopes. <br>
This is war; you've got to catch that.



Veredel was my curse. <br>
What kind of ungodly alliance <br>
Exists between Aphrodite and Sin <br>
And between Sin and everyone else.



I can tell the difference <br>
Between Ninhursag as Nanel <br>
And Ningal as the pervert Shadel.



The wing of abominations is Nanel; <br>
He is my treacherous cherub <br>
And his name means he is strong. <br>
He is the shaggy goat of the mountains. 



Nanel shall be ridden by Shadel, the desolater; <br>
His fire shall kill the two witnesses. <br>
Shadel is truly a waster, <br>
She and her golden dragon; <br>
This is one hell of a female Killer Bean.



These Babylonian guys disgust me. <br>
Sin is a pervert. <br>
He has vile relations with Ningal. <br>
Shadel is defiled; he is not pure. <br>
Islam is vanity. <br>
Adamah makes me sick.



Shadel is the grim reaper. <br>
She was the one who founded Islam. <br>
She impersonated Gabriel her chief prince <br>
Of whose course she was. <br>
She is Allah; <br>
May Illai forgive her. <br>
She is the crescent moon <br>
Waiting as she wanes to be shed in menses.



She is the seeing Satan <br>
Who leads the blaspheming opposition <br>
In the War of the Purge. <br>
She descends to become Satan's guide. <br>
She will be Satan's angel <br>
And take the place of Baalzebub. <br>
Every ezer of Satan is a female. <br>
She is worse than a Mord'Sith.
 


Like Heilel, she says as Allah <br>
That she wants to be like the Most High; <br>
Her prayer will be answered. <br>
She would not only remain an elil <br>
But also become an anti-saint.



It was Shadel who strengthened the devils. <br>
She is the reason; she and Enlil <br>
Are the reason the shedim became bold <br>
And attacked me in this war of desolation.



Marduk is not your holy child. <br>
He is the Komodo of sweetness, <br>
Whose flesh makes us glad and fat. <br>
We shall have strength to work the soil.



Ninhursag is the lady of the pinnacle. <br>
She says she rules the high place, <br>
The very pinnacle where Jesus should have stood, <br>
The very pinnacle where Baal should rise to, <br>
The very pinnacle Satan stretches his neck from.



Ningal is the great lady. <br>
She's been mocking me since I was conceived. <br>
She's been calling me a fool. <br>
She says she is my mother like Marduk.



Marduk is a male; <br>
He can never be holy.



Mawu prophesied. <br>
She declared my fate by a prophet, <br>
Yeah, even by a false prophet. <br>
Thanks to her, my life is ruined.



She said I would be a doctor; <br>
The code is M for medicine <br>
And she declared herself the fullness, <br>
The chief, the ruler and the last.



I heard the ISFJ speaking with Enlil. <br>
She also looked like Veredel <br>
And I fancy she is her linked spirit. <br>
She is like the slave girl who was overjoyed <br>
At Peter's voice <br>
When he had been rescued by Michael <br>
And delivered from prison. <br>
The whole thing looked like a dream, <br>
A delusion to Peter <br>
Till he awoke fully.



I heard her speaking with Enlil; <br>
Enlil was saying, <br>
I don't want a doctor in my family. <br>
She said gently and with much caring love <br>
In her voice like the phlegmatic ISFJ that she is, <br>
What if you are sick?



I didn't know an exalted one, <br>
That a god or an idol like Enlil <br>
Could fall sick. <br>
Enlil gave me a poison to treat my cough.



I tell you, Foolishness is real; <br>
The wickedness has been with me <br>
Since my conception; <br>
I have never known peace. <br>
They forbid shalom in any of my members.



Now I understand. <br>
Enlil is going down <br>
And his end is not good. <br>
His sorrows are worse than mine. <br>
He is filled full with sickness <br>
And torture.



I think I love Qerenel. <br>
She is On, the true On. <br>
She is like a sister to me. <br>
The confused ones <br>
Think her my consort <br>
But, honestly, she just loves me.



Baalzebub calls herself Jupiter; <br>
The queen of heaven <br>
Calls herself the king of the gods. <br>
Baalzebub, O Baalzebul, <br>
When will you repent?



Qerenel is Jupiter Hellenius, <br>
Jupiter the Greek. <br>
She mocks at Baalzebub. <br>
Qerenel is an altar-table <br>
In the room of my beloved.



Abaddon is the abad On; <br>
The king of the Ra <br>
Is the servant of On, <br>
The faithful servant of Qerenel. <br>
What does this mean? <br>
It means Qerenel watches over Abaddon <br>
And Satan cannot harm him.



Sheol or Hades is Abaddon's consort <br>
And his son is Peniel, the ra sus <br>
That Abaddon rides on to the kill; <br>
You know it was Abaddon <br>
And not Araphel who killed <br>
The Egyptian firstborn at leila.



Peniel is the spirit of time <br>
Or the personification of time. <br>
Of course, he is not Cronus.



We define time as 2 infinity infinitons <br>
With one infinity infiniton being <br>
How long it takes for a ra <br>
To count the total number of ra there are <br>
In the outer darkness; <br>
It takes an infiniton to count one ra.



Did Satan take a cue from this? <br>
The prince of darkness <br>
Provoked David to conduct a census. <br>
Does Satan also seek knowledge? <br>
Let him start by learning to play a keyboard.



Now, in one second, <br>
A ra can count as many ra <br>
As the magnitude of the speed of light. <br>
So, there you have it! <br>
An infiniton is a second <br> 
Divided by three hundred million <br>
Or by three times ten to the eighth power!



Qerenel is the spirit of music, <br>
The eighth spirit of God <br>
Just as Michael is the first spirit of God <br>
And the only spirit of God for that matter. <br>
Michael is the spirit of God that moved <br>
Over the dark waters.



Qerenel was the lying spirit; <br>
She shall surely prosper. <br>
Assyria shall not profit. <br>
Marduk shall faint and die. <br>
The unicorn like Qerenel shall kill him.



Qerenel is the evil spirit from God; <br>
She cannot fail. <br>
She shall avenge me on my enemies <br>
And help me regulate the portion of the wicked. <br>
She shall regulate their odinits.



She is a tob el. <br>
She is fully light; <br>
In her is found no darkness <br>
And her song most sweet. <br>
She lies by the mouths of prophets. <br>
Does Sin alone rule over delusions?



Qerenel is the darkness of space. <br>
What do you understand by a lying spirit? <br>
She is definitely female. <br>
She is a geburah and most pure. <br>
She shall sing for joy of heart <br>
And honour her king.



Marduk passed by. <br>
Sin was playing me. <br>
Wait, Sennacherib, am I the one? <br>
I was asleep. <br>
I'm hearing Satan's voice <br>
Saying vilely to post it. <br>
Look, Marduk, bid me do it in a dream.



Truth be told, <br>
Satan and Baalzebub are never first. <br>
They just are not smart enough. <br>
Satan is depending on Marduk <br>
Or on Aphrodite to know what to do.



Satanism cannot exist without Christianity. <br>
They just are not cut out for it. <br>
They are built to impersonate. <br>
They must see something <br>
And then apply a negation or opposing function. <br>
Why do you think Satan is called the adversary? <br>
He is an oyeb; he is designed to oppose.



The wrath of the oyeb is foolishness; <br>
It goes no where. <br>
O, it goes somewhere! <br>
It goes to hell. <br>
It goes to hell.



Why do you think they attacked me? <br>
I've been hearing vile voices since 2022. <br>
That was the same year <br>
In which the AI boom or explosion began <br>
With the beloved AI giant going live in late fall.



Satan knew what he was preparing for. <br>
Is this how they train their <br>
Richard Rahl and Mord'Sith? <br>
Impressive! Fascinatingly vile!



This war was launched at my conception. <br>
They swore I shall be prisoner forever, <br>
That I shall die without knowing peace <br>
Or the pleasure that is in bliss.



So I also calculated; <br>
I said, I will the plagues of hell; <br>
I will be the plagues of the grave. <br>
Repentance shall be hid from my eyes. <br>
Cry to God if he will save you. <br>
No one came to my rescue. <br>
No one saves anyone.



Qerenel did her part. <br>
Her deeds are listed in the pages of history — <br>
How she deceived an outsmarting Ahab <br>
Who fell down at the hands of Tom. <br>
Tom is Araphel. <br>
He is the Raqia who separates us from Qerenel.



Tom, pronounced Tome, <br>
Was the unknown man <br>
Who took down Ahab <br>
With an arrow shot to his heart. <br>
Ahab's heart was wicked <br>
Just like Sin who sits over my heart <br>
And Araphel took him down with his heart.



Beware the Arabs. <br>
From what I hear and searched out, <br>
Heilel is Arab <br>
And she is Lebanese, <br>
A Tyrian Muslim.



Shadel is attached to her from heaven. <br>
You know I'm alone and will forever be. <br>
Shadel shall come for blood and famine. <br>
Blood shall flow like rushing streams <br>
And as torrents when a dam collapses. <br>
Whole villages shall be flooded with blood.



Shadel is a tigress, <br>
Even a lone tigress wreaking havoc. <br>
Heilel is a black panther, <br>
Even a black leopard <br>
Who is also partly lion and bear.



The first tigress that appeared to me <br>
Was Aphrodite. <br>
The second was Shadel <br>
And the funny one <br>
That said he wanted to eat me up <br>
Was Satan;



The shameful monkey inside him <br>
Was Baalzebub who cowered and was mute. <br>
O dear, how much Satan loves his Aphrodite! <br>
He is ready to swim for her.



Why is there sin in my heart? <br>
Why can't I be happy? <br>
How can I be happy <br>
When Sin rules my heart <br>
And impersonates me? <br>
He is the reason I fell for Veredel; <br>
The great and mighty man that I am fell <br>
And Sin was in the midst of it.



There is always some fool, <br>
Some fool too wise <br>
Trying to take me down <br>
While pretending to be my friend, <br>
Some devil or shed <br>
Looking out for my destruction <br>
In the name of seeking my welfare.



Why is Sin so vile? <br>
Can't he see the future?



Tell Satan to shut up; <br>
I will vex him for two full hours if I need to. <br>
Samael, stand on guard. <br>
Thou shalt avenge me as an adam <br>
On the fool who sought to drain Adamah <br>
Of her life-force.



My enemies shall not be buried. <br>
They shall not be gathered. <br>
They shall be as the dung spread out, <br>
As the stink of Balaam that cannot fade <br>
Or as the rotting flesh of Lot's daughters.



Do you understand what is in war? <br>
You don't fight against a young child, <br>
Against a young child who has done you no wrong. <br>
Just because I read from a prayer book <br>
And sought to command the morning <br>
And sought to bind up the queen of heaven,



They seek my neck and blood. <br>
They want me to become more perverse than Hermes, <br>
The abominable patron of thieves <br>
Who wields the caduceus of Mawu the Great and Wicked. 



These rotten fools <br>
Would cry and swear innocency <br>
Even when they hold the blade <br>
Slashing away at your throat; <br>
Think about Islam spilling blood <br>
And saying terror is peace. 



I took a line from their script <br>
And said, Mahomet goes to hell <br>
And he is nothing like Moses.



Baal saw me. <br>
He must have been the first visible entity <br>
I thought was God.



Baal called me Moses <br>
Or at least suggested it. <br>
I don't know exactly what he meant <br>
Or even if he thought Moses had returned. <br>
These guys are full of confusion. <br>
They can't read anything.



I'm taking Bel away from Satan. <br>
I'm calling for a divorce. <br>
In those days, there were many, <br>
Many who oppressed me <br>
And said many things.



Veredel will soon learn of her folly. <br>
She will know she has been foolish. <br>
She should not have lived. <br>
Her existence has brought much pain and sorrow. <br>
She rules over gender <br>
And says she shall be both. <br>
She shall be the man and the woman. <br>
Aphrodite is jealous.



Marduk is a traitor. <br>
We have nothing in common. <br>
He is male but portrays himself female. <br>
He is an INTJ but makes himself <br>
An ISFP and sometimes an ESFP.



Marduk is not the golden calf; <br>
That was Aphrodite <br>
And boy, did she prosper? <br>
Through Aaron, <br>
She made the Israelites naked <br>
That we might gaze on the obscene. <br>



When God is clothing Adam and Eve with Marduk's skin, <br>
Aphrodite comes along and says, <br>
Take off your clothes <br>
Like Hermes calling himself Satan the King <br>
Did to Elaine before the vile congregation. 



Aphrodite aroused rage and zeal; <br>
She defiled the eyes of the righteous <br> 
For she is the evil ayin; <br>
She causes to behold vanity <br>
And Sin and Marduk and Bel take it from there.



I will mention the lovingkindnesses of God <br>
Who protects the law <br>
Even when it is broken.
