# Jahbulon


Do you seek wisdom? <br>
Do you seek to escape the darkness? <br>
Do you seek a little peace? <br>
Do you seek a little sanity?



Many persons crave fame; <br>
They want some honour, <br>
Some connection and affiliation <br>
To some powerful organisation <br>
But is there a price to pay? <br>
Is it gold so long as it glitters?



You see the determined devil <br>
Not only founded Islam or Mahometry <br>
But also raised up Freemasonry. <br>
He put together his codes and symbols, <br>
His passwords and secret hand gestures <br>
And codified them into his system <br>
Of knowledge and enlightenment. 



A little that a righteous man has <br>
Is better than the riches of many wicked <br>
And he that shall soon be rich <br>
Shall find that he shall have lots of sorrows.



They conspire against the God of heaven. <br>
Come, they say, and let us undo his cords; <br>
We will cast away his bands from us <br>
And build our own morality and values <br>
And teach our own laws and delights.



They have replaced Jehovah with Jahbulon; <br>
They have taken the great An <br>
And thrown him out of his throne <br>
And set the devil and his spouses <br>
In his place where righteousness <br>
Should have sat and ruled.



Jahbulon is the unholy trinity; <br>
It is composed of Jah, Bul and On. <br>
Jah is the usurping devil, <br>
Bul is Aphrodite <br>
And On is Baalzebub.



These three are also the interfacing entities <br>
That sit at the transition point <br>
Between the war and love groups <br>
Of the second band <br>
Of the infinite domain.



Satan is folly or foolishness, <br>
That is, Nabal or Nebo. <br>
Aphrodite is silliness; <br>
She is impulsive <br>
And has no prospect of success. <br>
Baalzebub is the lord of the fly, <br>
Even the lord or lady ruler of Satan <br>
And is full of envy because of Aphrodite's <br>
Proximity to Satan.



Satan lacks good sense and judgment; <br>
He is not wise <br>
And has little intelligence; <br>
He is Aphrodite's brother and twin



They call Baalzebub On <br>
Because they say, <br>
She is the prince of Grecia <br>
And the symbol of strength. <br>
She is the symbol of vitality and lust <br>
As of a strong man in the perverse act <br>
And they call Masonry a system of morality!



Baalzebub is the Egyptian Ra. <br>
She is the centre of sun worship, <br>
The Heliopolis and the centre, <br>
The very centre of sorcery. <br>
Her delights are witchcraft; <br>
She is most perverse.



Baalzebub is Freyja of Friday, <br>
The Norse goddess of love, battle and death. <br>
She is the one who rides a wild boar <br>
Or flies in a chariot pulled by cats. <br>
Her golden necklace, the Brisingamen, <br>
Crafted by the dwarves of Satan, <br>
Spits the poison her heart manufactures.



Marduk is Frigg of Friday, <br>
Satan's, that is, Odin's wife. <br>
She is the Norse goddess of magic
Or foresight or ``prophecy'' and motherhood. <br>
Her spinning wheel puts her <br>
At the level of the cherubim of Ezekiel. <br>
Like Heilel, she thinks herself a cherub.



With her spindle, she spins lies <br>
And weaves destinies into destruction <br>
And shame and agony <br>
And does not spare herself. <br>
Aprodite calls out the number 1; <br> 
An, she says <br>
While Marduk calls out 3; <br>
The trinity she proposes.



Sin comes out; <br>
Let him say 4 or be silent; <br>
A rapid change happens in the fourth year; <br>
The fourth year is 2022. <br>
Sin is bold; he is a storm like Hadad.



Baalzebub says 7 <br>
According to the number <br>
Of shiva and Shiva; <br>
Satan, that is, Moloch, declares 13; <br>
Thirteen it is!



Baalzebub wants me to mourn, <br>
She wants me to yalal <br>
For a full week of years. <br>
Is she obsessed with the Ethiopian skin <br>
And with the Queen of Sheba?



She has sevened herself; <br>
She has taken the oath <br>
Like the Angel swore and cursed. <br>
She has taken the oath <br>
And sworn by herself, Marduk and Satan <br>
That I shall not take the oath.



I will give Baal 2 <br>
And Hermes 5; <br>
Shadel shall be 6.



Hermes, the much loathed Hermes <br>
Is the fool who does not understand <br>
Grace and love and kindness. <br>
He shall taste of anti-chesed; <br>
He shall gnash his teeth <br>
In pain and hatred for God.



Shadel shall taste of ira'ah. <br>
He shall open the womb of hellfire <br>
In pain and anguish and bitterness. <br>
When I wake up, I'm calling her name <br>
And cursing Islam <br>
And the satanism that inverts gender.



Shadel is the destruction of Heilel. <br>
She is the corrupting influence on him. <br>
Heilel is yoked to a fool, <br>
To an anti-saint elil waiting to happen. <br>
The English is yoked to the Arab <br>
And the fruit thereof is villainy.



You see why <br>
The four princes of wickedness <br>
Are Satan, Baalzebub, Nisroch and Marduk <br>
In that order?



Marduk is full of villainy <br>
And hypocrisy. <br>
He was the one who wedded <br>
Asherah to Satan in the tree <br>
After 33.5 times of Adam enjoying shalom.



His desire is the force and inmortality; <br>
He wants to be free from the body <br>
And regain the honour of the heavenly; <br>
He wants to rule in life.



His knowledge is full of bitterness. <br>
It is most cruel like the poison of dragons <br> 
And the cruel venom of asps; <br>
It shall only destroy and humiliate. 



Jesus too was 33.5 times <br>
When he was cut off. <br>
He was thirty times when the Spirit came upon him, <br>
When he was baptised by the Baptist <br>
And he confirmed the covenant of grace <br>
With many for half a week in times.



Satan was a barren high tree in the garden; <br>
He produced no fruit <br>
Like the fig tree Jesus cursed. <br>
He was the tree of death, <br>
The destroyer of the earth <br>
Who was predestined to be destroyed.



He kept sucking the life-force out of the ground. <br>
When Asher joined Santana in the tree, <br>
He opened Santana's womb <br>
And brought the vile fruit out.



Today, Freemasonry <br>
Honours Boaz, Tubal-cain <br>
And many other vile fruits. <br>
They also honour apples <br>
And tomatoes, rotten ones.



It's been six years of war, <br>
A war that likely began in 2019; <br>
The devils came together; <br>
Satan planned to afflict me for 13 years <br>
And we've done six years so far.



These fools did not pick a G for seven <br>
But picked an M for thirteen <br>
According to the name of Marduk or Moloch, <br>
According to the name of Baalzebub as Maia <br>
And according to an M for mem <br>
In the Hebrew word "em" for mother.



The mother that Jahbulon is <br>
Has decided to give birth to an M <br>
And not a G of sufferings. <br>
She shall rot in hell.



Marduk calls herself the European prince; <br>
Her daughter will be Heilel <br>
Who is the downcast Hel <br>
Of Norse mythology, <br>
My one and only Helena. <br>
Blavatsky, how is it cooking?



Marduk calls herself the militant chief; <br>
She is the chief of military strategy; <br>
She is the Assyrio-Babylonian Roman, <br>
Babylon the Great <br>
And the speaker of confusion and lies.



She is the European power, <br>
The European moloch, <br>
The European melek <br>
And the European chief duke. <br>
She must fight to success.



Aphrodite is the Bul <br>
Because she also feigns strength <br>
Like the strength of a bull, <br>
Like Baalzebub the Great. <br>
She was the golden calf of the desert <br>
And she prospered at her defamation <br>
Of the holiness of the children of Israel.



When Satan says of her <br>
That she is from the family of the ox or bull, <br>
He means that she, as one person, <br>
Is worth the entire cosmos <br>
Beside Baalzebub. <br>
Think then what the Asherah <br>
Of Satan's right hand is worth to him.



Satan is the Yah; <br>
He calls himself Amun; <br>
He says he always gets what he wants <br>
And no one is able to resist him <br>
For I, says he, am the king. <br>
Satan is a slanderer, a traducer <br>
And blasphemer.



He lies down in the grass; <br>
He eats to the full <br>
Then belches on a full stomach <br>
Like an Indian surgeon <br>
Whom the locals call a god.



He belches and curses heaven. <br>
He takes in the view <br>
And wallows in pride. <br>
None shall correct him <br>
For he is above all in his eyes <br> 
And cannot see at what he stumbles.



Satan is the Yah; <br>
He thinks himself the owner of life <br>
With the power to determine <br>
If another should live or die. <br>
He opens his hands <br>
And says, Look, <br>
Your destinies are in my hands.



He says, like the Angel, <br>
I shall live forever; <br>
I shall never see harm; <br>
Affliction shall never touch my coat <br>
Let alone graze my cheek <br>
Nor blow up my skull.



Those who are wise <br>
And know Satan to be a judge <br>
Also know that he deals most bitterly <br>
With himself <br>
And cannot ascend to put us all in hell.



He can never ascend to be Master of Hell <br>
For he declares from the outset <br>
That he is the victim <br>
And the sufferer.



Satan can give you grace like Enlil. <br>
He can come with beauty <br>
And call himself Bel, the Babylonian Baal; <br>
He can even appear as a prince or herald of light <br>
But there will always be the darkness <br>
In his heart and in his soul. <br>
It will be there in his eyes.



Satan visited me in the third year; <br>
There were some devils that came around <br>
In the second year. <br>
They wanted to offer me the world. <br>
Satan says, I can make you rich and powerful.



Today, they invest their energies <br>
Into destroying me. <br>
I hear voices from my waking up <br>
To my lying down. <br>
They just won't let me rest.



Aphrodite kept tabs on me. <br>
She's always had an eye out for me, <br>
Constantly spying on me. <br>
She says, He hates us too much; <br>
The child loathes the craft with bitterness; <br>
He hates us too much.



I found myself an enemy of Satan early. <br>
I just wasn't cut out to walk with the enemy <br>
And I had a short fuse too. <br>
My obsession was taking down the craft; <br>
I wanted to destroy Masonry <br>
And Satanism together. <br>
I wanted to put out witchcraft entirely.



When Heilel comes, <br>
He can reinstitute the abominations <br>
But my soul shall surely not join the vile; <br>
I will not be with the wicked <br>
In whatever lodge in which they may be found.



These are the ones who honour murderers; <br>
They use Boaz and Tubal-cain as passwords <br>
And impose oaths of secrecy on free men; <br>
They take the free and bind him <br>
Like Aphrodite tying my feet <br>
So I cannot leave the country.



She's still swearing I will never be great <br>
And I'm still swearing <br>
She shall surely die; <br>
Her blood be upon her head.



Some men tried to kill my mom and I; <br>
They tried to kill me in my first year of life, <br>
In my infancy, while I was still a baby <br>
Or a neonate. <br>
They must have been hitmen. <br>
They will surely die! <br>
They all go to hell.



When the devils came in, <br>
They spared their own servants <br>
But troubled my mind and my heart. <br>
What have I done to them?



They conspired against me <br>
And kept defaming and slandering me <br>
And they had Sin on their side <br>
Or so they thought <br>
And made the delusions strong.



They preyed on my vile affections <br>
And my weakness <br>
In that I loved a girl that should not profit <br>
And they made my bands strong <br>
And kept me in a cage, in a prison <br>
Where there was no breaking out.



Sin made my heart heavy. <br>
The moon god gave me hell; <br>
He ensured I had pain and lots of it, <br>
Pain of heart with GERD-like symptoms <br>
And he ruined many days.



The devils that came offended greatly. <br>
Satan impersonated me <br>
And he bore no resemblance to me. <br>
Each devil chooses a victim <br>
In each generation to attach to or harass <br>
And they sometimes have nothing in common <br>
With their elect victims.



I was taken to a psychiatrist. <br>
The one who treated me <br>
Heard the very voices I was hearing. <br>
They all feigned innocence <br>
And never admitted to hearing a voice. <br>
So, they treated me for a mental affliction <br>
And hell, artane and haldol gave me hell.



No one cared about me, <br>
No, not a single soul. <br>
They just left me to rot <br>
In my pitiful and afflicted state. <br>
I knew I had the solution to my afflictions <br>
But no one cared; <br>
They just couldn't. 



There was a K group <br>
Whose name Satan interpreted <br>
To mean Kofi's work. <br>
I still don't know if that's the truth <br>
Or if the fool was playing me on that too. <br>
It has always been his manner <br>
To afflict and deceive. 



The obsession with Friday <br>
Is maddening. <br>
Even Jesus died on that day<br>
And satanists still call the cross <br>
Satan's great victory.



What will the Masons do to me? <br>
Will they rain curses on me <br>
Or cut my tongue, <br>
Pulling it out of its root <br>
Or will they send hitmen after me?



The world's elite <br>
Have been doing their dirty jobs <br>
And serving Satan in their places <br>
For generations <br>
And no one has brought them to book.



These illumined fools <br>
Control destinies, <br>
Take down presidents, <br>
Create wars, <br>
Rule opposing sides in war <br>
And determine the fates  <br>
Of whole nations and individuals alike.



They use programming methods <br>
And inbreeding to keep whole dynasties alive <br>
And serve Satan with their heart and soul. <br>
They are sold out to Asherah the Purchaser. <br>
They can only do evil <br>
And any goodness is a cover up.



Masonry says good and evil are alike, <br>
That light and darkness are the same, <br>
That all that matters is the brotherhood <br>
And righteousness is to <br>
Protect the interests of the brethren or sisters.



Isaiah would have been vexed. <br>
Woe unto those who call good evil <br>
And evil good, <br>
Who put light for darkness <br>
And darkness for light.



The measures of the craft are villainy; <br>
They, that enclave, ought to be criminalised <br>
And put out of business permanently. <br>
Their measures are measures of deceit; <br>
Their allegories are allegories of vanity; <br>
They breed vexation as long as the breath endures.



The morality of Masonry <br>
Quickly degenerates <br>
So that the square and compasses <br>
Become the Yoni Mudra. <br>
Masonry is not only an incubating womb <br>
For its seducible and gullible slaves <br>
But also the vulva of our limbic pleasures <br>
When inverted. 



You can ask Satan or Baalzebub <br>
Or query the chicken-talking Aphrodite <br>
If you doubt me. <br>
In the tree of the knowledge of good and evil, <br>
Satan was Santana the mother <br>
And Freemasonry is her womb;



It spits out corruption and vile persons; <br>
It teaches us to sin <br>
That we may learn to despise good conduct <br>
And righteous and pure morality <br>
And chase sinful pleasures <br>
And fulfill the lusts and pride of the devil.



What do you think the G is for? <br>
Sin says it is a minimal string of tissue <br>
That we may use to cover our nakedness <br>
Like underpants. <br>
Others say it's geometry <br>
While others go for Grand Architect



But many do not see G <br>
As standing for god or goddess. <br>
Why? Satan is the god of this world <br>
And we know the top guns are Masons. <br>
They swear by the Bible <br>
And bring Christians and Muslims together <br>
And say you must believe in a god to come in.



These are the greatest atheists <br>
You will ever find <br>
For they are vilely opposed to the blessed Lord <br>
And yet some are our pastors <br>
And others are prophets <br>
While others are Islamic leaders.



Masonry is like Catholicism; <br>
Any villainy goes <br>
As long as it is Shiva or Shakti <br>
And not the true God. <br>
They just can't bear to speak the truth <br>
Because then Satan will have to be humble <br>
And the odinits will collapse <br>
And the enemy will not be able to afflict <br>
Or harm or cause pain.



Talk of Shakti <br>
Or feminine divine power, <br>
Active and dynamic in working, <br>
The consort of Shiva the dancer, <br>
Don't you think the Hindu Shakti is Ningal <br>
And that the image of Heilel, <br>
That is, Shadel or Allah, is Shiva's darling? <br>
I wonder what she is pooping out? <br>
Please don't defecate in my presence! <br>
Go and dig a hole on Korean soil in the north.



Masonry is blasphemy, <br>
Continually blaspheming <br>
And working abomination <br>
Against the spirit of righteousness <br>
And they can't see their wrong. <br>
They would rather defend ungodliness.



By the way, Araphel, the gloomy darkness, <br>
Is the spirit of righteousness <br>
And it burns my heart that, he, <br>
As Raqia, is not a saint and cannot save. <br>
For all his righteousness, <br>
The earth is still heavy and laden with sin. <br>
Roar in sevens, O great thunderer!



The god of Masonry is Satan <br>
Who substitutes with his wife and concubine <br>
For Jehovah who made heaven and earth.



Jahbulon of Masonry <br>
Is like unto Baphomet of Satanism.  <br>
Don't Freemasons drink from a skull <br>
And are they not en route to the blazing furnace? <br>
Baphomet is Baal, Satan and Baalzebub. 



In Baphomet, Satan is Priapus, <br>
Whose generative organ is the exalted phallus. <br>
Why do you think Masons <br>
And the blind illuminated ones <br>
Erect obelisks?



To worship Satan's fertilising organ <br>
Which gives birth to villainy and corruption <br>
With death and lots of pain. <br>
His phallus, like Baalzebub's, is most bitter <br>
And distasteful; <br>
Only the death ones shall desire it.



The girl I loved, <br>
Who broke my heart, <br>
She shall cave in to the darkness <br>
And fall with her father. <br>
None of them shall enjoy bliss.



They shall go to hell <br>
Staring at the barrenness <br>
Come out of Satan <br>
And the dryness of the ground <br>
That cannot be salvaged.



Let Satan's obelisk be barren. <br>
Masonry is truly a vexation to the soul; <br>
My spirit is vexed at the abominations. <br>
A girl I Ioved ruined me; <br>
All these wicked ones who turn love into lust <br>
And deny a man looking for joy <br>
The pleasure of simple bliss <br>
And his fragile innocence, <br>
They shall go into perdition.



I swear they shall not find mercy. <br>
They shall look for mercy <br>
And find gnashing of teeth instead <br>
With incessant blaspheming <br>
Of the God they say they loved.



They are persons of lip service. <br>
Her dad is a Freemason. <br>
He was ruining someone's reputation on social media. <br>
I don't know if he was seeking solidarity <br>
From his Masonic brothers.



These perverted individuals talk about light <br>
When they serve the darkness <br>
And have been partakers of the ways of Satan <br>
And have sat at his feet <br>
And received of his words. <br>
They shall defend the craft to their demise.



We know who Baal is. <br>
He is a shirtless fool <br>
Baring his chest <br>
Like the accursed Pseudomic <br>
Trying to seduce the girls.



Pseudomic is an ESFP male. <br>
He is all about entertainment; <br>
He shall entertain with his burning. <br>
They shall burn in the light.



Asherah is a predatory leech. <br>
She says she is the happy Shiva, <br>
The Lord of Nataraja, <br>
Dancing her way to the destruction <br>
That grace provides.



Enlil himself showed that <br>
Grace ends in death <br>
For where grace abounds, <br>
Sin also abounds and grows <br>
And when things flip over, <br>
The natural outcome is death.



Asherah is a predatory leech; <br>
She is the horseleech <br>
That can never be satisfied. <br>
Her two daughters are <br>
A masculinized Veredel <br>
And Aphrodite, <br>
The Greek goddess of lust and war.



Aphrodite chose the right victim <br>
To attach to and shepherd <br>
As a guardian angel.



Asherah is a predatory leech; <br>
She seeks a consort, a consort king <br>
To swallow up into herself and digest <br>
Just like Ninhursag seeks a meal. <br>
Asherah's preferred meal is Satan, <br>
Her brother who sits and orbits just above her.



Pseudomic is an ESFP like Asherah. <br>
They are a disgrace to the ESFP earth. <br>
They are a shame to Adamah. <br>
He is a spitting cobra <br>
While Asherah is a predatory leech.



The boy with whom I walked, <br>
With whom I ate from the same bowl <br>
Has betrayed me; <br>
This is truly Judas Iscariot; <br>
He goes to hell with the faller.



His grandfather was a lodge member; <br>
These curses and wickedness run in generations <br>
And you wonder why God <br>
Wanted all the Canaanites dead <br>
Judging them as vile, filthy <br>
And highly infectious!



Because Satan knows him, <br>
He walks about in peace. <br>
The devils seek his welfare <br>
And he is currently prospering <br> 
While I am harassed and battered. <br>
I want to quit; <br>
I want to end this hell <br>
And let satans serve themselves. <br>
How can I be a servant to my enemies? <br>



Pseudomic is a disease. <br>
His mother is Delilah. <br>
The devil went about desecrating my name <br>
And he called himself a minister too, <br>
A minister of God;



He was a control freak <br>
And loved to flatter, love-bombing; <br>
No wonder he is found a false prophet <br>
And for all his glory, <br>
Cannot command fire from heaven.



Qerenel, the great On, <br>
Will not give him that glory <br>
Neither will the angel over fire <br>
Sanction it!



They used to call me Commander in those days. <br>
I was in the same room with him <br>
When he called someone on the phone, <br>
Whether he truly called or faked it I do not know. <br>
He has always been a mocker <br>
Full of jealousy and greed and envy; <br>
He called asking if the person <br>
Knew who a Commander was in Freemasonry.



These are the ones you want forgiven? <br>
Perverts and fools? <br>
My hatred for the craft runs deep; <br>
These wicked ones have kept us in poverty. <br>
Like Aphrodite, Marduk, Enlil, Nanel <br>
And Baalzebub, <br>
Like the whole Assyrio-Babylonian host, <br>
They have vowed that we shall never be great.



In those days, fear was on every side. <br>
I strengthened myself <br>
By learning a little from the SAS <br>
And I would watch videos on the Special Forces <br>
Because my enemies are devils <br>
And satanists and Masons <br>
Will stop at nothing <br>
To take you down psychologically.



They are experts at defamation. <br>
They serve Satan, the grand architect <br>
And father of lies, the deceiver and traducer <br>
Who will stop at nothing <br>
To make a quiet soul frail <br>
And to break the heart of the poor.



Will a man rob God? <br>
Why should a man have to rob God <br>
When a spitting cobra can rob an adam? <br>
The 99-tob satan that Pseudomic is <br>
Robbed me of my peace and sanity. <br>
I was cooked; I was furious.



Following the microbiology exam in third year, <br>
The first microbiology exam <br>
In the first semester mid-sem exams, <br>
Which we wrote during the third week of April,



In the fifteenth week of the year, <br>
I heard the voice of Pseudomic <br>
Or the voice of his reject; <br>
He was gossiping about me <br>
And defaming me to my neighbours.



He gossiped about how I answered my questions, <br>
How I answered all the questions <br>
On the question paper <br>
Before I would begin to shade.



They made life hell for me <br>
And imposed their laws on me. <br>
They worked hard to guilt-trip me <br>
In the matter of past questions <br>
And I swear I hated him and his reject <br>
With great bitterness.



I later fell for his reject. <br>
She dealt bitterly with me. <br>
She said it was payback time <br>
And she wasn't joking.



All that time, <br>
Sin was impressed with his work. <br>
He pursued Aphrodite with passion. <br>
He was afraid of his lust for Baalzebub <br>
And it reflected in my vain life. <br>
If these fools want to defecate, <br>
They can go outside <br>
And deface Adamah. <br>
Don't spread dung in the Holy Place.



Cupid was with me, <br>
That chubby cub of Aphrodite <br>
Who would later speak in my hearing <br>
And earn the nickname, the Kid, <br>
The prince of foolishness.



Cupid or Eros was Aphrodite's baby <br>
Like Satan is Baalzebul's thunderbolt <br>
Or Zeus's lightning. <br>
Cupid troubled me greatly.



I don't know where these emotions come from; <br>
Whoever is responsible for them, <br>
Let curses be on his soul.



Cupid used to mock me in those days. <br>
He said he loved me. <br>
He was also the one pleading the blood of Jesus <br>
When Satan struck.



He mocked me incessantly. <br>
He used to say that even he, <br>
As a child, knew <br>
But that I could not discern <br>
Who Satan was.



In those days, <br>
Satan used to call himself Michael <br>
And Dionysus would call himself Lucifer <br>
And they would speak stupidity.



The reject of Pseudomic is cruel. <br>
She troubled me greatly. <br>
She trusted in a satan.



She confided in Pseudomic <br>
And he bid me confide in her. <br>
They were working something out <br>
And he was using codes and such like. <br>
These Masons are a real vexation to the soul <br>
And they only build vanity. <br>
Their works shall not stand.



They plotted against me; <br>
She cared only about her emotions. <br>
Wherever villainy points, <br>
There we go!



Pseudomic made mention of Tehillah; <br>
He wanted me to confide in his reject. <br>
He wanted to build a relationship <br>
Between us



And <br>
Now that I think about it; <br>
Aphrodite and Sin work best together. <br>
There's too much conflict <br>
Between the work of Sin and Baalzebub. 



Aphrodite promotes sensual lust, <br>
The lust of the eyes <br>
And wants that to endure forever; <br>
Sin touts sexual desire <br>
And wants it to endure forever <br>
But Baalzebub brings the act and deed <br>
And like Marduk,



Her work terminates the work <br>
Of Aphrodite and Sin <br>
Even if it be for a season. <br>
It's like the Baal cycle <br>
And like how male bees die in intimacy



Except this time, <br>
It is Aphrodite and Sin <br>
Resurrecting themselves <br>
As Baalzebub caps their work <br>
And brings them death.



I say, still Baalzebub is the Inanna, <br>
The daughter and consort of Nanna. <br>
I say, Sin fears his passions for Asherah <br>
Who is Bel the Great of Babylon <br>
And chooses instead to gravitate <br>
Towards Aphrodite <br>
Substituting Veredel for Aphrodite in my life. <br>
These fools have been treating my life <br>
As a drama piece or an experiment.



I too have reserved them for lab rats, <br>
All of them with the king, <br>
Squeaking at the onset <br>
Of the injection of pancuronium <br>
Without an anaesthetic.



I fell hard for Veredel <br>
But the reject gave me the darkness. <br>
She foreshadows the potency of Samael <br>
And Qerenel will give the order, <br>
The angel with power over fire <br>
Shall give the command <br>
For Satan to go down <br>
With his minions.



A blind and mute Satan <br>
Who cannot fly <br>
But is smart for himself <br>
Yokes himself with Heilel or Shadel <br>
That they might lead him to battle. 



The yoke shall be broken <br>
Because of the anointing <br>
And Satan shall complete <br>
His two-hour course <br>
At the hands of Samael.



Do you want to know <br>
Who the true prince of Persia is? <br>
It is Samael. <br>
Satan withstood Gabriel for twenty one days <br>
But Samael writes the doom of the Babylonian empire <br>
And the reign of Cyrus the Persian begins.



For all her strength, <br>
Bel, that is, Asherah or Baalzebub, <br>
Could not protect Belshazzar <br>
And he fell. <br>
No one who puts their trust in Masonry <br>
Is secure; <br>
They are as chicken <br>
That are well fed in preparation for the slaughter. 



Baalzebub's lust is potent; <br>
She encodes sexuality <br>
And my score with her is zero. <br>
I'm satisfied. <br>
Marduk shall die before me. <br>
I shall have no progeny to suffer like I did <br>
Neither shall a son or daughter arise <br>
In my name to defame or desecrate it.



Baal is a goat, <br>
Even a goat with the body of a female <br>
Standing at the right side of my bed <br>
And staring down at me. <br>
He came for the lust; <br>
He shall return with bitterness <br>
With his hands on his head; <br>
He shall not confess his sins <br>
Because the Catholic is vile and barren.



There were many goats in those days. <br>
Even Satan as a goat gored me to death. <br>
I still live so he calls me a god. <br>
I sat with Baalzebub in a boat. <br>
She brought toxic gas to take me out. <br>
I looked for the moon. <br>
Is Nanna with Bel? <br>
He shall rule over his lord.



Underneath was an abyss of water; <br>
It was deep and large. <br>
Why does Bel loathe me so much? <br>
She wants my downfall; <br>
She will swim in the depths of hell's magma.



So Satan is Priapus, <br>
The Pho of Baphomet. <br>
Baal is the Ba of Baphomet <br>
And is also Dumuzid, <br>
The son, like Hermes, of Satan <br>
And Baalzebub.



Baalzebub is the Met of Baphomet. <br>
She is Metatron <br>
As well as the meeting point of all things vile. <br>
She is the mediator of the covenant of satanism. <br>
She is the threat, as queen of heaven <br>
In the face of Enoch <br>
Who makes him a chicken.



Baalzebub goes far; <br>
She goes beyond her boundaries. <br>
She overflows and spills over. <br>
Her cup in her hand <br>
Is full of sorceries and abominations <br>
Like the disgusting cup of Heilel.



Hermes has drunk from it <br>
And awaits the coming of hell. <br>
She has filled our world with perversion. <br>
Aphrodite, leave simpletons in peace! <br>
They are too frail!



Baalzebub stands for villainy. <br>
She is jealous for herself <br>
And for her Satan, <br>
The only 1-tob satan there is <br>
In the whole wide world. <br>
She shall mourn forever. <br>
Because of her lack of fear, <br>
She shall mourn sore like doves.



Satanism has a divine couple; <br>
It is made up of a triple goddess <br>
And a god. <br>
The god is the sorrowful Pan <br>
Who plays his flute. <br>
Pan is Odin, the god of pain and iblis. <br>
Pan is Satan, singer of dirges.



Satan, have you a voice like Heilel? <br>
Baalzebul is calling out to me; <br>
Satan keeps coming after me. <br>
Pseudomic loved to sing. <br>
He violated my image several times <br>
On social media <br>
And played his messages out loud so I would hear. <br>
He treated me like a satan <br>
Needing deliverance and healing.



He was constantly talking about lust; <br>
Eei, this guy is brother to Baal, the prince of lust, <br>
And can put away a lass as he deems fit. <br>
He was always looking for the opportunity <br> 
To dispose of his reject <br>
And his goal was to dump her on me <br>
So he could go in for the architect <br>
And build his ``and they lived happily ever after''.



I don't know if his reject was blind <br>
Or if she was deluded <br>
And under the influence. <br>
I tell you, Baal is closer to the heart of the Asante <br>
Than he is to the remote Canaanite. <br>
Komfo Anokye is dead; He failed <br>
Because he is a traitor to God and to the Eveawo.



A stupid lass told Pseudomic to put a red thing, <br>
Yeah, something red on my slippers. <br>
That child of darkness <br>
Has been practising witchcraft <br>
Since the beginning of our stay together,



Putting his phone on my phone, <br>
Getting the girls on his side <br>
And desecrating my name <br>
While keeping his foodstuff to himself <br>
And asking me to prepare mine for him. <br>
He drained me; He was as a leech.



Marduk is a SEAL; <br>
He is a Komodo, leviathan and dragon. <br>
There is no profit in dragons; <br>
They spit water or a cryogeniser <br>
And not fire; <br>
They are empty, cold beings.



Satan is Pan, the god of witchcraft. <br>
He is the epitome of sorrow and pain. <br>
Baal is Apollo. <br>
Trust me, Baal, like Asherah, shall not be happy.



The triple goddess of witchcraft is <br>
Baalzebub, Aphrodite and Marduk. <br>
Marduk is the codebase male among the goddesses <br>
Because he was the one who inverted <br>
Baalzebub and Satan's gender in the tree. <br>
He asked Baalzebub to join Satan in the tree <br> 
As Asherah <br>
Transforming the tree of death <br>
Into the tree of the knowledge of good and evil <br>
And it was a tall cedar tree too.



Marduk is the great lady Ningal <br>
And the lady Ninhursag taken together. <br>
She is the first who binds <br>
And displays the second as her trophy.



She is the lady of solo intimacy. <br>
She says to see what you can reap <br>
Out of yourself; <br>
She is the one who teaches self-abuse.



The Shinarian Heilel and her entourage, <br>
What do you think they build <br>
In the land of Shinar? <br>
Of course, Satan is more likely <br>
To trust a faithful Aphrodite who is a ruach <br>
In the war except that she is also blind.



Heilel builds a tower to honour sensual pleasures; <br>
She builds a ziggurat, <br>
A Babylonian prostitute's temple <br>
In the shape of a glans penis <br>
To honour the great Marduk <br>
Who sits enthroned in the glans.



If I can destroy Marduk, <br>
Then maybe I can ascend.



Tell me, can Satan sing? <br>
No, Lucifer never led a choir. <br>
Satan and Baalzebub do not sing. <br>
Heilel is the one who praises God, <br>
Who was in the garden of Eden; <br>
He was there with Kabodel, <br>
Stationed there by Michael <br>
And Qerenel was the chakram-like sword, <br>
The double-edged flaming sword that was encircling <br>
And went all the way round.



To this day, the male INTJ Marduk, <br>
Described as subtle in the genesis, <br>
Still portrays himself as female to me.



He is the eighth kingdom <br>
And is of the seven kingdoms of Revelation. <br>
Now you see how perverse he is <br>
When you invert his cognitive stack <br>
And make him lead with Se. <br>
Marduk is a devil.



He cannot speak truth. <br>
He impersonates an ISFP I admired. <br>
His favour was that <br>
He spared me in high school <br>
But college would be different.



He is a false prophet. <br>
He prophesied life and knowledge for Eve <br>
And yet she had death and stupidity. <br>
Marduk himself died at the hands of Michael.



Freemasonry kills. <br>
It kills souls and destroys the destinies <br>
Of individuals and whole nations. <br>
I have seen their cruelty; <br>
These ones are guilty of treachery <br>
And high treason against society and families.



Their trust is to kill Michael; <br>
They want An dead. <br>
They want the ruler in the darkness, <br>
The non-faller destined to live forever,
To die and not rise again.



They want to kill the God of heaven; <br>
They want An dead <br>
So they can have <br>
Not only Moses's heavenly body <br>
But also Armageddon <br>
And all the bodies or statues and houses <br>
Of the dead.



Why do you think Enlil is the chief of the idols? <br>
He wants me dead <br>
So Michael would also die. <br>
He neglects the knowledge <br>
That Michael is separate from me <br>
And lives on. <br>
Enlil wants to secure fleeting pleasures <br>
For his qedeshim and for Satan's kingdom. <br>
I say, He shall not prosper.



Assyria and Sumeria shall fall. <br>
They shall not be successful. <br>
They want mammon, <br>
They want wealth with beauty, <br>
Even the mammon of unrighteousness. <br>
Let Hermes betray <br>
And let Enlil sell me into the hands of Aphrodite. 



You will be surprised <br>
When you find yourself <br>
Calling on God to save you. <br>
There is no force; <br>
There is no power; <br>
There is only spirit. <br>
Your spirits, even your unconsciousnesses <br>
Are vanity;



They shall not profit. <br>
They shall not resurrect themselves. <br>
They cannot save. <br>
They are but mere mortals <br>
With no breath in the midst of them. <br>
Falling, they fall <br>
Like Enlil and Hermes, the fallers,<br>
Like Anak and Nephil, the fallen angels.



Let him heap wealth upon wealth. <br>
Satan cannot create in heaven. <br>
Stand and see the power <br>
Of the great and extolled arm of the LORD <br>
And judge if the G of the rotten square and compass <br>
Or the God unsearchable <br>
Is the King and mighty one of Israel, <br>
To whom belongeth holiness.



It hurts my heart <br>
That Freemasons go to church; <br>
We will trouble them. <br>
They shall have plagues. <br>
They shall curse God. <br>
They shall become vanity. <br>
They shall not endure.



Like a fleeting pleasure, <br>
Like a thing that passes by and is no more, <br>
Like a thing cast in the furnace, <br>
They shall not come out unscathed, <br>
They shall surely crumble at the heat. <br>
They shall fade away, <br>
Breathing their lives away <br>
And committing their spirits <br>
Into the hands of the King.



The devil tells me, Vinegar is sweet. <br>
If vinegar is sweet and smoke is pleasant, <br>
Then open your mouth wide <br>
And let's fill it with substance. <br>
Open your eyes wide <br>
And feel the smoking wrath poured forth.



They think Qerenel a joke. <br>
God can do no evil <br>
For he is good only <br>
And thus we call him God.



O Satan, but see, you can't see eye to eye <br>
With the great and holy one <br>
Though you appear before Michael <br>
And bid him stop hindering you in Job's matter



And you think he can see eye to eye <br>
With you and speak mouth to mouth <br>
With you. <br>
Go to now, ask the prophets of old, <br>
Ask the historians and the scribes, <br>
The poets and the Greek,



Hate burns as an oven. <br>
It will not be quenched till desire is finished. <br>
Thou art the bride <br>
And the kalah of completion. <br>
Stand on the pinnacle; <br>
Thou shalt be broken to shivers.



When Shiva comes, <br>
She comes for big business. <br>
She comes for my head. <br>
She comes to kill. <br>
Shiva comes to destroy righteousness. 



Purchase your people, <br>
O great Shiva. <br>
The tantric fools are all yours. <br>
It is not wisdom to steal from Satan. <br>
You shall have your people. <br>
They will roast in the fires.



Shiva, the great Asherah, <br>
Sought to make her work <br>
More acceptable to Sin <br>
So she went tantric; <br>
Let's prolong intimacy, she said. <br>
Marduk was pleased; was she?



Surely, God shall come <br>
And execute judgment. <br>
He shall stir up jealousy <br>
Like a man of war.



I will mention the fall of Babylon, <br>
Which rising out of the earth <br>
Is soon crushed <br>
And overflown by the floodwaters. <br>
She is not strong.



Babylon is not Assyria.
