# God


Save me, O God, from delusion; <br>
Redeem me from the hand of Marduk <br>
And do not let the wicked rule over me; <br>
Do not let us see eye to eye.



Save me, O God, from the wicked <br>
For I have waited for thy salvation, <br>
From the cruel wolf, the dragons, <br>
The cow and the viper. <br>
Save me from the jawed leech.



In your splendour, save <br>
And in your beauty <br>
That we might praise thee <br>
As long as the sun and moon endure.



My God has to be honourable, <br>
The most honourable, <br>
Exalted, exalted above all. <br>
He has to be the King, <br>
The prince of the kings of the earth.



He has to be a gibor, <br>
A mighty warrior <br>
Commanding strength in the fields <br>
And crushing the skulls of rebels.



My God has to be perfect, <br>
Perfect in holiness, <br>
A just God and upright, <br>
Without iniquity and sin.



He shall endure as long as Zion <br>
And rule to the bounds of time. <br>
He shall suck of the abundance of the seas <br>
And grace and great glory <br>
Shall be his oil from day to day.



There is none like unto the God of Jeshurun, <br>
Who passing through the garden, <br>
Takes Marduk by the horns <br>
And skins him alive <br>
And clothes Adam and Eve with his scaly hide.



The everlasting God is with me <br>
For a sure defence and a mighty fortress <br>
And he shall rule over the strong <br>
And be praised by the mighty <br>
And there shall we see <br>
The jealous and silly one <br>
Slain by her imperishable envy.



O God, when thou didst lay <br>
The foundations of the earth, <br>
The morning stars were there, <br>
The four time entities — <br>
Shachar, Mishchar, Araphel and Qerenel — <br>
Sang together in perfect melody. <br>
They were the first musicians in history.



Thou didst create the earth on the first day <br>
And Adamah remained among the maim; <br>
She remained as a tob among the tobs. <br>
On the first day, you made Mammon <br>
And you made Armageddon. <br>
You made the ras, the outer darkness.



On the second day, you made the mansions, <br>
The inanimates to house the angels <br>
And on the third day, you finished heaven, <br>
You finished your creative work in the celestial space. <br>
On the third day, you made the angels,



Even on the same day <br>
You laid the foundations of the earth; <br>
On the same day you gave Adamah her body.



Satan saw your work and was jealous; <br>
His heart smote him in the chest. <br>
There was vexation in Satan's heart <br>
And envy and jealousy in Baalzebub's <br>
And they sought to overthrow creation.



Say, was it not Baalzebub herself <br>
Who said wrath and vexation <br>
Killeth the foolish man <br>
And that envy slayeth the silly one? <br>
Who is the foolish man? <br>
Is it not Satan? <br>
And is not Baalzebub the deluded one?



Baalzebub, O, how hated you are! <br>
She is smitten to the full <br>
By the blows of Sin; <br>
She is full of delusions <br>
And would have desired <br>
To lead the rebellion <br>
In the War of the Purge.



She says, I am <br>
And there is no one else. <br>
She is the angel of Satan <br>
And the Purchaser whose image provokes to jealousy <br>
Yet she exalts herself above Satan <br>
And makes herself the father of the fall <br>
So that Satan as the effeminate Santana <br>
Might lie beneath her.



Baalzebub calls herself Asherah, <br>
The one who shall never be widowed <br>
And who shall never see the loss of children <br>
Because she has purposed <br>
She shall never be married <br>
And shall never give birth. 



She brags about her strength <br>
And calls herself On. <br>
She swears by her lustful strength; <br>
I am stronger than Satan, she declares.



Baalzebub is hell-bent; <br>
She came for the kill; <br>
She has no plan; <br>
Her end goal is my demise <br>
And the death of Michael. <br>
She wants Armageddon.



She says, If any must sing, <br>
They must sing to me. <br>
Have you ever heard Asherah singing? <br>
She is too deluded <br>
And filled full with delusions of grandiosity <br>
Like a haughty and wanton Jewish lady <br>
With her nose held up high in the air <br>
Who walks about making noises <br>
With her ornaments and declares to all her riches.



Baalzebub calls herself the queen of heaven. <br>
She says, I am the lady of kingdoms; <br>
I give grain and bread <br>
And they bake cakes unto me <br>
And I provide rain in his season.



She sits and slanders her own mother's son; <br>
She opens her mouth to slander the son of Mishchar. <br>
She slanders Michael like she does my name; <br>
She has torn my honour into shreds.



I will be sown in dishonour <br>
And raised up in honour; <br>
Shame and disgrace shall not rob me <br>
Of my glory and promised peace. <br>
Surely, Baalzebub shall fade away <br>
Like a menstrous cloth that women cast away.



Satan was a sinner from the womb <br>
Like Marduk and Baalzebub his siblings <br>
But he thought, like Joker, <br>
He could deceive others <br>
And get away with a laugh.



Baalzebub is very bold; <br>
Her boldness arose from her delusion; <br>
She fell hard into Sin's ditch. <br>
Satan is the deceiver <br>
But Baalzebub is the antichrist.



She hates the Christ; <br>
She hates Michael and the elim <br>
And she declares it boldly <br>
In the gathering of elohim <br>
And before the hosts.



So who is the antichrist? <br>
Baalzebub is the first antichrist; <br>
She is before Heilel in villainy; <br>
Baalzebub is an ESFP female <br>
But Heilel is an INTP male;



The antichrist must be a female; <br>
Heilel shall be a female <br>
And earn the dishonour of perversion; <br>
She shall lie with and defile herself <br>
With kings even to hell.



She and Baalzebub <br>
Are the Jezebelian Babylonian mother <br>
Who rides the dragon. <br>
They shall drink blood to drunkenness. <br>
Baalzebub, thou art doomed <br>
And destined for darkness;



Prepare blindness for her <br>
And make her dumb; <br>
Thou art no star; <br>
Thou shalt not give light; <br>
This iron shall not profit; <br>
Isis and Ishtar are dead. <br>
They are in the realm of the dead.



When Baalzebub came to me, <br>
She feigned love; <br>
She impersonated one I had fallen for; <br>
She impersonated the reject of Pseudomic; <br>
She had her cold icy hands on me;



She made my paths deep and slippery; <br>
She led me towards hell; <br>
She meant to procure me unto Satan or death; <br>
She sought my grave demise.



She appeared around the time of the exams <br>
When I was going to write <br>
My first end of year theory exam <br>
In fourth year; <br>
That was in July!



She was there <br>
When I was writing <br>
My Chemical Pathology paper, <br>
When I was preparing <br>
For my Chem Path viva <br>
And when I was studying <br>
For my Sys Path viva.



She was there in the room <br>
We went to wait in <br>
As we waited for our turn <br> 
For the Sys Path viva



And the reject was there too,<br>
The one who was musing <br>
On the nature of these voices <br>
And wondering if they were ghosts.



Is Baalzebub your ghost <br>
From the grave, from the land of the dead?



So, Aphrodite and Cupid <br>
Handed over the baton to Baalzebub; <br>
Two to one, heh, <br>
While Satan remained a constant presence.



Baalzebub is screaming <br>
And an accursed Aphrodite jumps in; <br>
Satan is calling and trying to distract; <br>
He wants my attention; <br>
They are consumed with folly.



O God, when you lifted up your hands <br>
To heaven, to the shamaim, <br>
You swore by one who lives forever. <br>
You swore vengeance and retaliation. <br>
You will not forgive.



Surely, a recompense is in order; <br>
Let the enemies of God be confounded. <br>
Confounded be all they that serve graven images, <br>
That boast themselves in idols <br>
And strengthen themselves in sin.



Who is as wise as Satan? <br>
Who is as stupid and foolish as the devil? <br>
Seeing many things <br>
And hearing many things <br>
And knowing many things, <br>
Yet he cannot know nor understand.



Who would go before Michael <br>
And bid him grant him access to Job <br>
That he might harass and destroy him? <br>
Later, he desired Peter <br>
And to this day, satanists <br> 
Wear St Peter's Cross as a venerated object.



Seek not unto vile idols <br>
That mutter and stutter. <br>
These idols are worthless. <br>
Even the great and honourable Rachel <br>
Desecrated the idols <br>
Of foolish Laban.



But you say, did she not die in childbirth <br>
For desecrating an elil <br>
And for profaning an abomination? <br>
O, mortal, do I not suffer <br>
Because I showed promise <br>
And hated the devil and his kingdom <br>
With bitter hate and vexation?



So, Satan fought against me <br>
And did that which has never before been done <br>
And has wreaked a devastation <br>
To go into the pages of history <br>
At the point of an iron pen;



He devastated me, <br>
He fought against me <br>
With his arsenals of slander <br>
And constant harassment <br>
And perverse desecration; <br>
His delusions were unleashed upon me.



I came down under multiple onslaughts; <br>
He said he would destroy me. <br>
He would make my remembrance to cease, <br>
To cease from under the heavens.



Marduk was with him. <br>
The abominable Enlil with Shadel. <br>
They conspired against me. <br>
They knew they were in for hell.



Concerning the vexations <br>
Which ye have done to me <br>
And the vile desecrations and desolations, <br>
Ye have not had the end in mind <br>
And will ye deal thus <br>
With such great cruelty?



Satan said I ought to be destroyed. <br>
I could not be admitted into his fold <br>
Because I could not keep <br>
The simple oath of secrecy. <br>
His problem, as was Baal's, <br>
Was that I liked writing <br>
And could not keep silent.



These fools do not know <br>
The awesome and stunning destructions <br>
That await them. <br>
Give Baalzebub anti-chesed <br>
That she might know what it really feels like <br>
To hate the great God with gnashing teeth <br>
And with bleeding blue gums.



Satan, you hate me <br>
But do you know how much I hate you? <br>
Do you read me? <br>
Do you copy? <br>
Do you know my innards?



When you impersonate me <br>
As does Sin, your brother, <br>
Do you have the future in mind <br>
And do you have all variables accounted for? <br>
Thou shalt lie down in sorrow! <br>
Prepare slaughter for Baalzebub.



Rachel shall live. <br>
Where is Baalzebub? <br>
Who killed Rachel? <br>
I do not know.



Rachel shall live. <br>
The ewe of God shall live.



Baalzebub, your birth pangs shall come. <br>
Thou art a gebereth, huh. <br>
Thy pain shall be bitter. <br>
It shall come upon the horseleech; <br>
Even cruel and wicked labour pains <br>
Shall come upon the ra'ah that you are.



I said to the devils, <br>
Do not put your trust in me <br>
Because I am your destruction. <br>
Cease the programming. <br>
I will give you the full satanism treatment. <br>
You shall be broken, all of you, <br>
Like the satanic mind-controlled slaves.



Do not worship Satan <br>
Because he will not profit. <br>
Seek not unto the sorceress and rebel. <br>
Do not put your trust in Ningal. <br>
Ninhursag shall not deliver. <br>
They are the perverts, the anti-saints <br>
Waiting to destroy you.



I will praise the Lord as long as I live; <br>
Let my bones sing the Lord's praise. <br>
Let todah boom everywhere. <br>
Wherever life does ring, <br>
Wherever the greens live on, <br>
Let voices of joy and rejoicing be heard.



Come and let us go into the house of God. <br>
There, we will write the praises of our God. <br>
There, we will sing to the name of God Most High <br>
Who alone doeth wondrous things, <br>
Even things past finding out



For surely thou art a God of judgment; <br>
Justice and judgment rests with thee. <br>
Thou shalt deal to them their portions, <br>
Each one according to their works



For thou wilt save the afflicted people; <br>
The Lord my God will enlighten the darkness. <br>
He shall reach forth the yad <br>
And his hands shall open to me in grace <br>
And lift me up from the dungeon,



From the dark dry pit of snakes <br>
Where are venomous snakes <br>
Waiting to strike at and bite Joseph, <br>
From the den, the horrible den <br>
Where are mighty lions <br>
Waiting to break Daniel's bones.



The Lord is my strength <br>
And the fortitude of my mind. <br>
Thou holdest me standing. <br>
You lift me up <br>
So that I do not slip and fall <br>
And you enlarge my steps under me.



He confounds the wise <br>
And takes away the glory of fools; <br>
He destroys the wealth of the wicked <br>
And at Qerenel's command, <br>
The deceiver and the host <br>
Are cast into the burning light, <br>
Paying for their sins <br>
In pains that cannot be fathomed.



Baalzebub sits still <br>
In the dust. <br>
The iron hastens to rust. <br>
Her strength is gone from her. <br>
There is no life left in her. <br>
I give her my pledge — <br>
Destruction is her reward; <br>
Destruction and dishonour unto her soul.



Has thou seen a widow before, <br>
A real one, one who has lost her soulmate? <br>
Bitterness, grave bitterness is Asherah's portion.



I will mention the lovingkindnesses of God <br>
Who gives me life and holds me up; <br>
Thou, O King, art Jeshurun <br>
And thou shalt not faint. <br>
You rule forever with a right sceptre.



I will dash Death in pieces. <br>
His stroke shall cease. <br>
I will smite him twice, <br>
In the outer parts <br>
And in the inward parts <br>
And he shall know that he hath offended <br>
And done very foolishly.



Next time, stand before me as man <br>
And call yourself God <br>
And ask me to believe in you <br>
And to hope in your mercy. <br>
You shall have death and sorrow.



Encamp round about Armageddon. <br>
Compass him about as about Jericho <br>
Yet ye shall fall; <br>
Ye shall not stand world without end. <br>
Ye shall surely perish <br>
For strong is the Lord God <br>
Who judges the sinners.



Give me goodness; <br>
Take not away from me righteousness; <br>
Never let me see want, <br>
No, not today, not tomorrow. <br>
Supply me daily with nourishment. <br>
Let me not pine away in my sins <br>
Neither let me waste away from want of vitality. 



The Lord who gives strength unto his people <br>
And brings righteousness as torrents <br>
And clothes with peace <br>
And gives hope and brings faith <br>
Will soon rebuke the slanderer. <br>
Lead the charge, O great God of the dawn!



O, Egypt, worship the King of Kings <br>
And pay homage to righteousness <br>
For the gods of Egypt shall not profit. <br>
Baalzebub shall not worship; <br>
She shall be mute. <br>
She is Isis.



Seth goes down. <br>
As lightning, he falls. <br>
He shall not rise up <br>
And the eye of Horus shall be blinded. <br>
Baal shall never see again.



When Baal appeared in my dreams <br>
As far back as I can remember — <br>
Then, I thought he was God — <br>
He called me Moses <br>
And I saw a man who looked stoic <br>
And was clad in a white long garment <br>
At about the age of sixty



Who passed in between two rows of people <br>
And was led to the slaughter; <br>
He walked on by himself <br>
And demonstrated no fear. <br>
Was he slaughtered? <br>
I didn't see the end of it!



Baal, Baal, he shot me in the head; <br>
Baal was in the confessional. <br>
I fear for the pastors of Ghana <br>
And for all prophets around the world; <br>
They destroy a lot of souls <br>
And can never be innocent.



O God, do they know thee? <br>
Do you know them? <br>
All these that prophesy in thy name, <br>
That swear by the king of heaven <br>
And forbid prayers to Michael <br>
But pray in the name of Jesus, <br>
Are they in thy books?



If Christ stands for praises and worship, <br>
If Christ wants there to be music, <br>
Even the sweet fragrance of the lifting up of hands <br>
Toward heaven and the opening of the mouth <br>
In praises and beautiful words,



Then Baalzebub, the antichrist <br>
Stands for the absence of music. <br>
She has been perverting all my music. <br>
Wherever I turn to on YouTube, <br>
This devil just won't let me or the music rest.



A man has got to be happy <br>
But Asherah is a killjoy <br>
And a parasite and plague. <br>
She is a blood-sucking horseleech <br>
And a cruel parasite in the cosmos.



She is an alternative Satan, <br>
The bringer of perversion, <br>
Sexual depravities and harassment <br>
Without peace and righteousness.



She shall destroy herself and many <br>
But Christ shall ransom my soul <br>
And deliver from the clutches of this hell. <br>
You will see in that day <br>
When bands are put on the devils <br>
And Hermes goes dumb.



Then, what will become of his brides. <br>
I am fed up of the lies of Hermes. <br>
Hermes is Ephraim. <br>
He is a Canaanite; <br>
He can only prostitute; <br>
He is a qadesh of Enlil.



Michael loved Hermes; <br>
He loved him while he was only a child <br>
But Jeshurun waxed fat and kicked. <br>
Thou art grown tall; <br>
Thou art waxen great.



Then, he forsook the God that cleansed him <br>
And lifted him from the mud, <br>
From eating swine's flesh <br>
And feasting on mud; <br>
He forsook God his father <br>
And went in to the queen;



He received commission from her hand. <br>
He betrayed his king <br>
And became the king of satanism. <br>
He became Satan the King, <br>
The ruler of the Brotherhood <br>
Replete with regional brides to defile.



I swear the law is looking for him. <br>
Araphel is calling for his destruction. <br>
Hermes compasses me about with lies, <br>
Ephraim compasses me about with lies, <br>
Declares a grieved Michael.



Hermes didn't quite get the memo. <br>
You certainly do not want to grieve the Holy Spirit <br>
With whom you have been sealed unto salvation.



Hermes despised his crown <br>
And cast it to the dogs. <br>
Do not cast your pearls before swine <br>
Lest they despise and disregard it <br>
And turn and rend you.



Judah is an eagle. <br>
Judah is really a bald eagle. <br>
He is a fisherman and fish-eater <br>
And Dagon and Eve are fishes. 



He goeth about preaching marriage. <br>
Judah is Gabriel. <br>
Gabriel, I want an armourbearer, an ezer <br>
Not a wife, not an ishshah.



Gabriel is still faithful  <br>
And rules with God. <br>
He shall ascend to become an el.



Gabriel troubled me <br>
With his prophecies. <br>
His prophecies messed up my life. <br>
I said this man lieth. <br>
Then, I understood — <br>
He spoke about Jesus and not me.



Give me peace; <br>
Where is the river <br>
Where all is still, <br>
By whose banks is calm?



Give me peace. <br>
What will you have? <br>
I have peace; give me peace. <br>
Give me peace; give me peace.



O God, you saw when Eve betrayed. <br>
She spoke to the Komodo. <br>
You saw when Marduk betrayed. <br>
You know the thoughts of their hearts <br>
And the things they have purposed; <br>
You know their inmost desires.



Give their desires to the wind; <br>
Let them eat grass. <br>
For the oppression <br>
And for the violence <br>
And for the onslaught, <br>
Let them gnaw their teeth for pain <br>
That they may know that the King <br>
Ruleth in heaven and earth.



So, Hermes shall be dumb. <br>
He shall be blind also <br>
Because he took not the log from his eye <br>
But sinned without remorse <br>
And there was no conscience <br>
To say, What am I doing?



He should not have departed <br>
From the glorious path; <br>
He should not have put his hand to the plough <br>
Then turned to look back <br>
Like Lot's wife did <br>
And gave the devil allowance <br>
To produce the abominable seeds of those two.



Grain is good <br>
And famine is a terror; <br>
Hermes, can you see into the future? <br>
Do you see the counsel of the Most High <br>
And can you perceive the decree gone forth? <br>
Dost thou know thy end <br>
And the bitterness thereof like that of Balaam?



Balaam shall not die the death of the righteous; <br>
He shall die the death of the uncircumcised, <br>
The death of the vile <br>
As of one reserved for the eternal darkness <br>
Whose light is crushed before the morning <br>
And consumed to the ends of the earth. 



Hermes, who gave Balaam counsel? <br>
Who is Baalpeor? <br>
Is she not the goddess of the opening, <br>
Thy mother that raised thee up <br>
And nurtured thee <br>
And taught thee the way of wisdom <br>
Which way is to violate women <br>
As a pervert that cannot be satisfied?



Hermes shall not see his brides anymore; <br>
He shall not behold the beauty of their forms <br>
Neither shall he speak to them <br>
To deceive them with soft words <br>
Only to return with three princes <br>
To tear the skin off the seducible.



You devils really hate humans, huh <br>
And you wonder what Satan was doing on earth <br>
As it is to this day. <br>
He is an idiot in toto.



Bread is good <br>
And manna is sweet; <br>
It is honey-crusted; <br>
Eat it to the full



And fill your bellies and delight yourselves <br>
In the abundance of the goodness of the land <br>
For the years of darkness shall be vile.



All that cometh, as saith the Preacher — <br>
That great Peniel, the enosh who strove with Jacob <br>
And called him a prince and Israel — <br>
Is vanity and vexation of spirit.



Peniel is a horse; <br>
His neck is clad with thunder. <br>
He is a geber <br>
And the angel who flies in the midst of heaven <br>
Having the everlasting gospel to preach <br>
To all creatures that are alive.



The message is simple: <br>
Fear God and obey his commands <br>
For he shall bring every work into judgment <br>
With every secret thing <br>
Whether it be good or evil.



Peniel is a horse; <br>
He smells the battle from afar off <br>
And laughs at the rattling quiver; <br>
He smiles at the sound of the alarms <br>
And trumpets and does not believe in fear.



I am dreaming of glory. <br>
Can there be peace, <br>
A little peace to each soul? <br>
There is no peace, saith the Lord, <br>
Unto the wicked.



Perchance, a little wisdom <br>
From time to time <br>
Shall make Baalzebub <br>
Feel like life is worth living. <br>
Some persons do become sober <br>
In their afflictions.



Do not get your hopes up. <br>
Baalzebub is a captive, a prisoner of war; <br>
She awaits death <br>
And shall surely not escape.



Enlil is gravely ashamed. <br>
He smashes his hands in anger <br>
At his foolishness <br>
And chases after more iniquity.



I shouldn't have been this cold, <br>
Even this icy cold as Death, he fumes. <br>
I will shut the mouth of my mind <br>
Because it troubles me that I live <br>
And my desires consumed me <br>
Therefore I sinned



For I sought Satan to please <br>
And feared and grieved my future <br>
And could not repent; <br>
Even Sin mocked me, <br>
A wolf parading as a lion.



Death, do you want to cross over, <br>
Even cross over into death? <br>
Thou hast suffered too much. <br>
Now, it's time to die. <br>
Baalzebub wants to be like the Most High. <br>
Heilel is dead;



My soul is inditing a good song; <br>
I want to peep into the first universe. <br> 
My pen is awakening; <br>
The blue ink rouses itself up; <br>
The white sheet is before me. <br>
The tablet is prepared.



I want to know who God is. <br>
Who is the great Maker? <br>
Where is his place? <br>
Where does he reside? <br>
Why is he so exalted and yet so meek? <br>
Who is he?



He passes by on the right side; <br>
I turn the head but he is not there. <br>
He is swift on the left side <br>
Like Gabriel flashing out of the east <br>
Or like Michael or Fear running to battle <br>
And rising for the kill.



Has thou found him, <br>
The perfecter of righteousness, <br>
He who makes the mountains smoke, <br>
That calleth for the fire <br>
And the smoke <br>
And speaks with thunderings?



Love is at the apex <br>
Of the dimensions of God. <br>
God is love itself. <br>
He encodes energies of love; <br>
He encodes the knowledge of love <br>
With power and the desire <br>
To demonstrate his love.



He cannot be subject <br>
To the influences of Pleiades <br>
And he is bound to no one <br>
As seen in the demise of Heilel <br>
And the promotion of Yirel over Michael. <br>
But he enforces love.



Mishchar is the Gaboah King <br>
And, yes, there are many <br>
That are higher than Time and Gaboah. <br>
Hamalkah is the spirit of life, <br>
Peace and righteousness; <br>
Judge, O great one made of jasper: <br>
Am I a sinner? Is my folly wicked?



Mishchar loves On. <br>
He loves the epitome of strength. <br>
The gibor loves the geburah <br>
Who is the altar-table in his room <br>
And his lord.



The nephesh loves the ruach. <br>
The soul of the adam <br>
Is bound with strong cords of love <br>
To the soul of the cherub and air seraph.



You know Michael is Mishchar's son <br>
But do you know Mishchar loves Qerenel? <br>
The brilliant sunrise loves the tob. <br>
She has been his delight throughout eternity past. <br>
He is the Spirit and she is the bride; <br>
Gabriel certifies and seals their marriage <br>
And all of heaven rejoices <br>
At the marriage of these two morning stars.



Has thou found the Unfathomable <br>
That we may appear before him <br>
And bow down, pay homage and worship <br>
And open our treasuries <br>
And bring forth gold, frankincense and myrrh?



When the Lord appeared, <br>
The earth shook. <br>
The earth trembled in herself <br>
And quaked before God. <br>
She quaked with the noise of thunder <br>
And gave her voice from behind the King.



Adamah was beside herself with joy; <br>
She has long waited for the salvation, <br>
Even for the salvation of her God <br>
And of her King. <br>
She lies down and waits. <br>
Everyone shall receive of thy portion



For the Lord's lot is his people, <br>
The inheritance that he has purchased, <br>
Even ransomed from the anti-Source <br>
And from the anti-God, <br>
From the jaws of death, hell and sin.



Ain't it strange that God <br>
And the anti-Source <br>
Should have a common enemy <br>
And that her name should be Asherah?



Everyone that shall fall shall be replaced; <br>
Let no harm come to the number. <br>
Thou of thy goodness has furnished blessings <br>
For the poor of thy people.



So where does God dwell? <br>
No one knows <br>
For he is alone <br>
And there is none with him



Yet he has a home in the first dimension <br>
Where are three times infinity plus one, <br>
Yeah, even that many entities. <br>
There, God has a body of hardest diamond <br>
And is radiant white and shining.



God is a shining star, <br>
The father of lights, <br>
The Shachar <br>
With whom is no shadow of turning.



Of his own will <br>
He begat us <br>
That we may be a kind of firstfruits <br>
Of his creatures.



We were born of the blood of the Lamb. <br>
We were born in the sufferings of the King <br>
And he washed us clean in his blood <br>
And certified our redemption <br>
And said, Surely they are my children; <br>
I too will uphold them with my arm.



I long to see the power of God's salvation, <br>
To see his glory and power <br>
As the ancients did <br>
And were not dismayed.



They took hold of the ends of the earth <br>
And shook the wicked out of it. <br>
They broke the bones of the sinners <br>
And confounded the wise <br>
In their sorceries and charming.



I long to see the power of Christ, <br>
That resurrection power <br>
That never gives up and never fails. <br>
It is strong and sure,



More firm and trustworthy <br>
Than great Mount Zion which cannot be moved <br>
But abideth forever <br>
And sits exalted above Armageddon.



There on Zion, <br>
Yirel, Michael and the select stand <br>
And the congregation receives of their words <br>
And worships from the mount of assembly.



Give glory to the Unfathomable. <br>
I wrote that he was unfathomable <br>
And I knew him not <br>
But he knew me <br>
And I am his <br>
And he is mine.



Say, O beloved Gaius, <br>
What is thine desire? <br>
Ask it to the depths of the abyss <br>
Or to the heights of heaven's sun. <br>
Thou doest well if you love God.



When God spoke from heaven, <br>
He looked at the beautiful ISFJ dove <br>
And declared, This is my beloved child <br>
In whom I am well pleased.



So, what do we know? <br>
We know God is with Yirel <br>
And the INFP Michael <br>
And they shall prosper <br>
For there is no repentance in God <br>
And he cannot alter his decisions <br>
For he is perfect and his work so.



What do we do then? <br>
Let us trust in God Most High <br>
Who frustrateth the works of the wicked <br>
And gives us righteousness <br>
Even satisfying us to the full.



Blessed are they that hunger <br>
And thirst after righteousness <br>
For they shall be filled. <br>
Though terrors should compass us about, <br>
We know the Lord lives <br>
And the anti-Source shall not prevail <br>
For there is only God.



Let praises rise <br>
For the Lord is about to rise; <br>
He shall make all the earth <br>
With the nations and the masses <br>
To tremble inside out.
