# Nature

I like the breeze, \
The pleasant cold of the heavens, \
The fine morning \
And the sweet dawn.

The trees swirl from side to side; \
They are beside themselves with joy. \
Lebanon rejoices; \
The fields skip like calves; \
The cedars dance like young unicorns.

Behold the grass of the field, \
These that are excellent in form \
And beautiful, a constant delight to behold.

They send their roots down \
With the trees \
And are established in the earth \
From whence cometh their nourishment.

The sun also smiles from heaven; \
Helios sends out his rays; \
Shemesh shines from his house \
And says, Behold me, behold me; \
All the planets revolve around him.

The moon draws near to earth. \
He pulls on the sea? \
What doest thou Yareach? \
Wilt thou uproot the oceans?

Day and night, \
Summer and winter, \
Springtime and harvest, \
Times and seasons, \
All things continue as from the beginning.

The pleasantness of the delightful is not new \
And the wickedness of the odious has been. \
That which was is that which shall be \
And that which shall be is that which shall be after it.

When you see violent oppression, \
Remember who made the heavens \
And remember who gave the command \
That the heavens should be made \
In the first place.

If the light does shine, \
If God does indeed rule, \
If he knows what he is doing \
And you cannot add to his work, \
Then keep calm and hold up your end \
For your end shall be beautiful.

I walked me among the grasses. \
I said unto the plants, \
To the young shrubs, \
Learn from me and be ye gentle. \
Do not turn aside to iniquity.

Do not depart from the way of understanding; \
Do not strengthen yourself in sin. \
Say not, Grace and glory to the wicked \
And I shall put forth my hand to the spoil \
And destroy the innocent

For this is the way \
And the fools are they that serve God \
And follow after righteousness \
And know not pleasure and the joys of sin.

I tell you their steps lead to hell. \
Therefore say not after their words \
Neither be partakers in the sins of the wicked. \
Rejoice not in transgression. 

Do not delight in sin. \
Give not thy strength to evil. \
Bend not thyself to seduction and delusion. \
Deliver thy souls as a lovely bird \
From the hand of the fowler.

I will declare the beauty of paradise, \
Even of the paradise of God \
Which Michael planted \
And made for Adam and his sons \
After him and with him.

The devil hated Adamah \
And was there to destroy the earth \
Even before Adam could appear. \
The Lord shall destroy them \
That destroy the earth.

Rejoice thyself in goodness \
And delight yourselves in the abundance of peace \
For righteousness shall flow down as a river \
And even Euphrates shall praise God, \
Even the Euphrates that Marduk trusts in

For Euphrates is tob \
And none of the tobs shall be lost \
And none of the ras shall fall. \
They shall be in the dwelling of justice \
And be satisfied with the abundance of ease.

Who is this that darkens the world, \
That brings death and sorrow \
And plague and famine, \
That dries up the grasses \
And causes the young shrubs to wither?

Who caused the fall \
And plunged the cosmos into chaos, \
That robbed us of peace \
And robbed the living of life?

Has thou seen the devil, \
Has thou seen his angel, \
Has thou seen his in-law?

Surely, there is an end. \
The iniquity shall stop her mouth \
And the wicked shall cease to see. \
Sight shall be given to the righteous \
And praises in the mouth of the holy.

O lilies, lilies of the field or pond, \
Be not like Iblis \
Who stood to destroy the earth \
And exalted himself \
Above every tree that is named.

His glory is his shame \
And he is Ishbosheth. \
He shall not excel \
For in him is much folly. \
Give him of his deeds \
And let him savour of his pains.

Draw near to the King, ye lilies. \
Draw near, draw near. \
Run from the devil \
And save your lives \
And deliver them from destruction \
For every green thing shall be saved; \
Be thou green in righteousness. 

The birds of the sky fly, \
The fishes in the sea swim; \
There is the fish gadol, \
Even the great and huge fish \
Which swallowed Jonah.

The birds of heaven fly, \
The golden eagle with the bald, \
The peregrine falcon and the owl, \
The swan and the hawk; \
They all fly in the open firmament.

The worm creeps in the soil. \
Like a creeping plant, it moves. \
The worm moves on her belly \
Like the snake that hisses.

Dan shall be a serpent by the way, \
A serpent that bites the horse's heel \
So that his rider shall fall backward. \
The viper did not bite the horse's heel; \
The viper bit mine.

Hermes shall be that serpent; \
He shall be the viper \
That bites the heels of Michael's horse \
So that Michael ben Mishchar \
Shall fall backward \
And Yirel shall be chief.

I was only a child \
When a scorpion stung me; \
It stung my right leg \
And I held that leg \
And my father anointed it with oil.

That scorpion shall not live. \
My brother quickly killed it. \
That scorpion is judged. \
It shall not make heaven.

In my university days, \
A centipede attacked me \
While I was at home. \
The crazy creature just wouldn't give up \
And it was fast too.

That wretched creature won't make heaven. \
I swear by my anger it shall surely die. \
It shall die the death of misery, \
Even the death of sinners \
With none to deliver it from hell.

The viper that bit me \
Bit me and snapped its jaws; \
It stuck its fangs into my flesh \
And refused to let go. \
It said to pour out blood. \
It said, I want your blood, \
I plead your blood.

So, I was attacked by a serpent \
But that wasn't the end of it. \
Three leeches also came for me. \
Yeah, the serpent struck early. \
It came out into the open very early

While the horseleech hid behind \
And waited her turn \
Till she was overtried \
And could wait no longer. \
She received the baton from a cow, \
The kind the Indians venerate. \
That cow is Aphrodite the leech.

That leech that stuck itself \
Unto my skin and flesh \
With his teethed jaws \
Has refused to let go \
As it is to this day.

She drinks my blood \
And keeps draining my life-force \
But I'm still alive, \
A wonder to the witnesses, \
Even to this great cloud of witnesses \
That watch on like Roman spectators \
Witnessing lions tear Christians in the arena.

I'm sure there is goodness in nature. \
It will not always be humans killing cows \
Or lions tearing zebras \
Or tigers eating goats. 

I'm sure there is goodness in nature. \
There will be the lion and the lamb, \
The python and the goat \
Lying down side by side \
Under a green vine tree \
And enjoying the beauty of the morning.

Michael as a lion \
Shall speak kindly \
To the Shunammite lamb.

O, who shall open the womb of Kabodel, \
Even the womb of Mishchar? \
Who shall unearth the seals \
And bring forth redemption, \
The redemption all creation groans \
And travails in birth pangs \
Longing to come to?

Do you truly desire righteousness \
And beauty, lots of beauty \
With excellence and the fineness of gold? \
Do you seek peace as for hid treasures \
Because that day shall surely come?

Heaven shall come out of God; \
It shall descend upon us \
And Adamah shall cease from her wrath \
And the seas from being troubled \
And the predators from devastating.

If a man would have peace, \
Let him know his strengths, \
Cause him to know his place, \
Even his place of peace \
That he may walk in it \
All the days of his life upon this earth \
And in heaven.

I lost a lot of peace \
Because I followed after vain persons; \
I hearkened unto the voice of a prophet \
As my parents reported it unto me \
And he must have prophesied by Mawu \ 
Or some other elil \
For the fruit thereof is most bitter.

By now, like the cedar fruit, \
You know nothing sweet \
Ever comes out of Mawu or Marduk; \
They should be called Mardulce \
For they mar every fabric of sweetness \
And then say that they have done no wrong.

If a man would have peace, \
Let him not follow perverts \
Nor run after them; \
Pull yourself away from Absalom. \
Do not be taken in with his beauty \
For Heilel shall not profit the rebel.

I had a little peace in the beginning; \
It was Mardulce who ruined me. \
She denied me first of every semblance of peace \
And that was not enough. \
She cursed my soul with lies.

Now, I'm stuck in wickedness. \
Have you any idea what my life feels like? \
It is as the prelude to hell, \
A kind of hell in its own right \
And a constant distasteful experience. \
None should desire it;
Baalzebub inflames it!

The prophets kept doing foolish things. \
They would not say anything wise. \
My dad held a hot phone to my ears \
And forced me to be prayed for. \
When I woke up the next day, \
I had headaches; \
I hated the prophets with bitterness

Because they despised me; \
They mocked me; \
They laughed me to scorn \
And the perverts called themselves holy.

There is one who has even sinned \
And despised fundamental laws \
And yet preaches salvation \
And refuses to reason. \
He thinks himself loved by God \
And yet Michael rejects him \
And Kabodel says, I know not his name.

Kabodel, out of whose womb comes life, \
Is the book of life. \
She rules over death \
And is superior to it. \
She is the saint from the infinity past, \
The other cherub with Heilel in the garden.

She also appeared to Isaiah \
And was the one on the right hand \
Above the enthroned Michael, \
The one who called out, \
Holy, holy, holy is the LORD of hosts; \
The whole earth is full of his glory.

At her voice, the posts of the door shook \
And the house was filled with smoke. \
She is the Son of God, the Bar, the Illai. \
She is Gaboah, the highest animate \
Of heaven and the celestial realm.

Heilel was the one who cleansed Isaiah's lips \
And forgave sins like Jesus did. \
How is it then that Heilel later blasphemes \
And becomes the little horn \
That curses the Ancient of Days \
And the Son of Man?

I once knew a girl; \
We did a lot of work together. \
We would chat on WhatsApp \
And answer questions together. \
I was mad and out of my wits \
Over her and she had me for a ride.

I once knew a girl; \
I felt so much peace being by her side. \
We could have achieved things together. \
Yes, we could have achieved a lot \
But she betrayed me and mocked me. \
She lied about me

And about my language. \
She played games with my mind \
And said that she loved it. \
She even called me Baby \
And I was furious.

She tried to make me \
Into a lust puppet \
Like another girl I came to despise. \
I found myself asking, \
What is wrong with this people?

You see, the girl I loved \
Gave me a lot of sorrow, \
Great afflictions \
From the second year \
And she loved and enjoyed every bit of it. \
Talk of psychopathology \
And psychopathy.

This one is like a satan for a human; \
Such a shame to be with one. \
She shall not profit anyone; \
Thou knowest it that it is true.

We could have achieved a lot together. \
She was even the one who encouraged me \
In the early days to post my poems \
And even to add a copyright symbol \
So it could not be stolen by another.

Her friend even calls her kind \
And I myself have seen her \
Donate a hundred cedis to a mate in need \
And I was there when she rejected my ten cedis \
And returned it to me like a saint

And I was furious at myself for sinning \
And went before the God of heaven \
Who is great in compassion \
And I taught myself knowledge \
As I had heard from the scriptures \ 
And learnt that the one who gives to the rich \
Shall come to poverty.

Of a truth, the devils heard my cry; \
They said they would fulfill scripture \
And make me poor. \
They said that they would ruin me \
And make me miserable 

So they came together \
And decided to afflict me mentally. \
They took me to the psychiatrist \
And I received a formal diagnosis. \
The doctor gave me my diagnosis \
And medicine.

It was formal; \
I had schizophrenia. \
Now, you satanists out there, \
I have made your work easier; \
It should be easier now to defame me \
Like you always do \
And have done to Dr Rebecca Brown.

Satanists are fools; \
They aren't half as intelligent as I am. \
The most intelligent priest among them \
Is as lame of wisdom as an ostrich \
That buries her egg in the sand \
And says it is a rock that shall not perish.

You satanists out there, \
Wait for Heilel and not for me. \
I am a grave disappointment \
To the kingdom of Satan. \
I do not profit the darkness \
But Heilel will. \
I am sure.

Next time, let's see if another lass \
Or woman will come \
And rob me of my peace. \
All the losers are damned. \
They shall not profit.

Give not thy strength to lasses \
Neither let chickens rule thee.

Aphrodite is a cow who speaks chicken. \
She is a leech and the firstborn of Baalzebub. \
Satan is a dragon who speaks flies and buzzing. \
Baalzebub is a leech who speaks duck. \
Nisroch is a duck.

I was there at a conference, \
A prayer conference actually. \
I heard dogs barking \
In the congregation.

Everyone heard dogs barking. \
We were all schizophrenic \
And hallucinating

Because the devils poured themselves \
Out upon us and the death ones yielded. \
No, the death ones actively did it.

That night, there was a heavy downpour \
As though to answer the prayer of the priest. \
The elements poured down water. \
The rain poured down \
Like streams out of the rock.

Once, there were thunderings; \
The devil spoke in the thunder, \
He said he had subjugated all powers; \
He was mocking Hermes \
As he called himself Lucifer.

God said, Ephraim is an unwise son. \
Who is Ephraim? \
Ephraim is Satan, the anti-INTJ \
But Ephraim can also be Hermes \
Or even Baalzebub.

I wonder why those who possess peace \
Do not guard it with jealousy. \
I wonder why no one cares about me. \
I sit in my place; \
I muse and I meditate. \
I wonder why there is no one with me.

When Jesus was on the cross, \
He called out, \
Eli, Eli, lama sabachthani? \
My God, my God, why have you forsaken me?

Pseudomic told me, \
Never ask why, \
Never ask why \
But Pseudomic is a fool. \
Surely, I can't heed his words.

Hmm, I had some questions for God. \
Could Pseudomic be right, \
The one who prays in toilets \
As though he prays to Baalzebub, \
The Yahoo and god of dung, \
The lord of the fly? \
That Baalzebub may well be Hermes also.

I had some questions for God. \
Did Satan pay me a visit \
To preach the message \
That he is the god who draws near to me? \
Is Satan mocking me like he mocks satanists? \
Is he trying to call me a fool?

Hermes stood beside me. \
I wrote that he stood behind me \
And that he is my friend and strong tower, \
That he is there with me \
When the storms are raging \
And that he fills me \
When my strength is draining.

I wrote thus \
Because, then, I thought that figure was Jesus; \
I didn't know that it was Hermes. \
I didn't know that he gave \
Heaven and hell revelations to Christians.

This false Jesus \
I saw leading me from Engineering Gate \
Away from the direction of my hostel \
As though to say he was with me \
In my afflictions and felt my pain \
And my disappointments. \
Heck, you orchestrated them.

This false Jesus was on the left side, \
Even on the left side of my bed \
At the time when I slept \
With my head away from the door. \
You remember how I said Baal was on the right side.

Hermes asked me what I wanted; \
He asked me like God asked Solomon; \
These perverts have corrupted the name \
Of the wisest man that ever walked the earth \
And put his name on the abominable \
Rite and religion of Masonry.

The Templars that despise the cross \
And urinate on it like Bohemians \
Are not satisfied but have returned \
To provoke us to anger \
With their villainy!

I did not hear Baal's voice openly harass me; \
He maintained far more decorum \
Than Satan, Hermes, Aphrodite and Baalzebub did. \
You know in medicine, \
You examine from the right side of the patient.

It is clear Hermes wanted to destroy my studies \
Just as Enlil wanted to. \
Thus, Satan's kingdom was partly divided \
Like iron and clay that cannot mix, \
Like nepheshim and ruachim that are divided.

Lucifer is Hermes \
Not just Baalzebub. \
Baalzebub is made of iron \
And dwells in 335‰ light \
But Hermes is made of steel \
And is 535‰ light.

His star is Tophet, \
Even the same Tophet \
That is prepared for the kings of satanism.

Pseudomic kept asking me for money. \
Buy bread for me; buy bread for me. \
He was from a rich family too. \
He is a spitting cobra not a leech.

He was trying to drain me of my resources. \
He was loaded with greed. \
He would not even return \
The Waakye seller's change to her \
Though I pointed it out to him.

He sought to discredit me \
After the manner of satanists and Freemasons. \
All they do is silence dissidents \
Whether through defamation like satans \
Or through cold-blooded murder.

So what is there in this cosmos? \
Some are good and some are truly vile \
But none can satisfy \
Like a saint can. \

Righteousness of character, \
A perfect and zealous nature \
Is to be priced above gold and rubies. \
You should be zealous for holiness \
After the manner of Melchizedek. 

God has sworn and will not repent; \
Michael shall surely become an el \
And attain unto knowledge \
Under the course of Melchizedek. 

Melchizedek ruled over the Jebusites \
And in his days there was peace \
For he is the prince of peace. \
He is Shiloh and Salem. 

Gabriel, let me ask you. \
Is Kabodel a male or a female? \
Is Melchizedek male or female? \
Melchizedek is the saint Kabodel, \
The image of Shachar \
And the sole saint beside Shachar \
For more than one infinity infinitons.

Melchizedek is Illai \
And Shachar is Elyon. \
Shachar is God, 

The doubly strong one \
Who combines El with On. \
He is made three times strong \
And rules by his yad in the yod. 

Heilel wants to be like Elyon, \
He wants to be like the Most High. \
The ben Yalal Shachar wants to yalal. \
He will have a lot of sorrow.

Baalzebub wants to be the One. \
She says, I am and there is none else. \
She calls herself On. \
She calls herself strong.

But thou art a weakling. \
Thou shalt no more be called tender and delicate. \
Thou shalt be like Samson. \
They shall put out thine eyes.

Baalzebub shall go into perdition. \
She shall fall and none shall deliver her. \
She shall go down into the depths, \
Even the depths of the pit. \
Prepare a wildcard against her; \
Prepare several wildcards that may afflict her. \
I am in the number.

Do you know why Heilel rebels? \
Do you know why Zuriel of earth rebels? \
Do you know why the Tyrian king and prince rebel? \
They rebel because they love the devils;

They are covenanted with the shedim in love; \
They rebel because foolishness \
Dictates so and they must oblige; \
They lack wisdom.

Why do you think satanism \
Is called the Brotherhood? \
Why do you think they destroy so much life \
And spill so much blood \
And curse the earth and curse God?

Heilel cannot bear to remain faithful to a God \
Who afflicts her own \
And destroys the shedim \
And humiliates Baalzebub.

Gabriel has bound Heilel, \
Even Heilel's heart to the shedim \
And she is become Satan's eye \
And the wielder of Satan's authority.

Listen to me, O little lilies, \
You who are excellent in form \
And have been declared precious; \
Listen to me, O lilies of the pond \
For the wicked shall consume away. \
They shall consume away standing.

Be ye meek and follow me. \
Pick up your crosses and choose peace. \
Pursue righteousness and be saintly. \
Choose holiness and cling to it

For the saints shall rule. \
They shall be the excellent in the cosmos. \
They shall bear rule to the ages \
Even world without end.

What do ye proclaim against me? \
What does the assembly of the cruel \
Devise against me? \
They only consult to cast me down; \
They are set in their ways. \
They can never be like the meek lilies.

I will teach ye excellent things; \
Sit down in the grass; \
Fold your legs and listen; \
Listen attentively to my words; \
Hear the voice that distils in your ears

For my voice shall be pleasant; \
It shall fall upon your ears \
Like the sweetness of the rain \
Or the light showers in spring.

It shall be like gold in the earth, \
Like a precious diamond \
That is worth dying for \
And even better living for.

It shall be your health and life. \
It shall deliver ye from darkness \
And your souls from the flaming grave \
And give ye hope and a future.

It shall establish your goings \
And make your paths broad; \
The narrow shall be enlarged. \
Ye shall grow fat and discern peace.

Spread your wings and soar. \
Look at the heights above. \
Spread your wings and soar. \
Lift up yourself and rise into the light.

Beauty is greatly to be desired. \
Fear the Lord and be great. \
Beauty is splendour; \
If it fades, many do lament.

I can imagine a lass, \
A beautiful lass. \
Her hair swirls in the sunlight \
On a bright new workday.

She is always happy; \
Her brother drew in my book; \
He drew a horse in my book \
And I added his name below it.

Do you know Sariel, \
One of the chief princes? \
You know Michael \
Who stands with and defends Gabriel \
But do you know Sariel? 

The chief princes are five; \
They are Michael, \
The linked spirit of Enoch, \
Gabriel, Sariel and Samael.

Sariel of heaven is in charge of bliss; \
Her codebase determines \
How happy each person can be; \
She is the bringer of bliss and joy.

Do you know beauty? \
Have you seen Sariel of earth? \
She is the most beautiful, \
The most beautiful lass \
I have ever set eyes on.

Truly, earth is tob. \
The beauty of nature is glorious. \
The green trees in the sunshine, \
The snapping turtle \
Crushing a watermelon,

Truly life is beautiful \
And full of spectacular sights \
And diverse beauties; \
Each has its own glory.

Walk along the seashore. \
Behold the flying fish. \
Go close to a dolphin \ 
Or make friends with an octopus. 

Walk along the seashore. \
Watch out for any crabs. \
Just enjoy the fine breeze \
And listen to the sound \
Of the waves \
As they crush on the seashore.

Truly life is full of life. \
Have you seen a lass as resplendent, \
Even as charming as my German Indian? \
She never got to hear it from me \
But, boy, was I moved by her beauty!

Truly life is gorgeous. \
Kabodel is your king \
And the sons of tsedek shall satisfy me; \
They shall make me glad \
More than wine the young men's heart.

Call out to your companions. \
Bid them come and see righteousness. \
Witness the works of the Lord: \
What devastations and desolations \
He has wrought in the earth.

He makes wars to cease \
Unto the ends of the earth. \
He breaks the bow \
And cuts the spear in sunder. \
He burns the chariot in the fire.

He makes the seed die \
And brings up the young herb \
And gives life in abundance. \
He gives the command \
And the foundations of the earth are laid.

Though earth be furnished a full body, \
Yet Shinar's ziggurat shall not be finished; \
It shall not be capped; \
It shall not be built to the ceiling \
Because we will destroy the works of Marduk.

Call the solemn assembly. \
This time, those in charge of the city \
Are not necessarily the seven spirits of God; \
Everyone is called to the battle, \
Even as many as shall respond to the Lord.

Come ye from far and near. \
Say ye to the princess, \
To the beautiful daughter of Zion, \
Thy King and father cometh; \
He rideth upon the holy earth that quakes; \
He runs to the kill.

Thy father, O daughter, \
Is a general; \
He is the chiefest of ten thousand, \
Even the chief in the cosmos. 

Michael shall go before him; \
The sun of righteousness \
Shall shine from the east. \
When the enemy shall pour in like a flood, \
The holy spirit shall lift up the hedge against him; \
The door shall be slammed in his face.

Come ye, come ye to the king. \
The daughter of Tyre shall be there too. \
She shall be preserved in the time of war. \
She shall rejoice with thee, O Kabodel.

Come, O daughter, \
Come, O beloved and elect of the King, \
Her name is Mishchar; \
She bears the insignia of Shachar. \
She has his image.

The virgins her companions \
That accompany her \
Shall enter the King's presence with singing; \
They shall sing and rejoice \
And sorrow and mourning shall be stayed.

Forget your father and his house. \
Come, join the king in his lair. \
Enter into the craggy palace, \
Come into the den \
And be protected from the war without.

The spirit of understanding said to me, \
The ENTP male declared to me and he said, \
The ivory palace that thou seest \
Is but a craggy den \
For his spirit shall live as a lion.

Upon mount Zion shall be deliverance; \
There shall be holiness \
And the Lord shall show us mercy

For strong is he that watches over our souls \
To save and to strengthen them. \
His name is the Lord \
And his remembrance is eternal, \
Even to the ages, world without end.

Know that in that day, Heilel shall live; \
The ben Shachar shall live and not die \
For great shall be the Lord \
And his peace and covering shall save.

Spread thy wings, O cherub, \
Fly thee to the west. \
Set up your throne in the great land. \
Rule thou over Europe.

Thus it shall be: \
Heilel shall rule over Europe. \
The daughter of Tyre, \
The daughter of Europa \
Shall ascend to Europe's throne and reign.

Glory, O glory to the righteous. \
Everyone whose name is in the book, \
Even everyone lacking the death trait \
Shall be saved and preserved.

At that time \
Shall the sleeping Saint be aroused. \
He shall rise up and stand \
Executing the judgment of a saint.

Everyone shall be saved, \
Even everyone who shall be found \
Written in Kabodel, \
Even everyone in the book of life.

But you say, \
How shall Heilel live? \
Heilel shall live for she is a princess, \
A lady and daughter of the king; \
She shall live to the King's glory.

The elect shall come to Jerusalem. \
There they shall encamp against us \
And there we shall destroy them \
And give up their bodies to the rot.

The feeble among the elect \
Shall have as it were the strength of David \
And David, even the chief, the strength of God. \
There, they shall batter the nations that offend.

War is decreed upon the nations. \
The end is drawing near \
And the nations shall know their shame \
And the people their glory that is marred.

Show decorum and honour. \
Honour the Lord and resist him not. \
Do not strive with God \
Though Jacob wrestles Peniel

For Peniel shall bless \
And Israel shall be blessed \
But the angel of the LORD shall curse \
And Meroz shall be cursed.

Rejoice, O ye saints with his people. \
Your brethren that thrust you out, \
Your nations that pursued you \
Shall fall down slain before you \
As in the day of Esther in Shushan.

They encamped against the camp of saints. \
The fire of God came down. \
It consumed them with their hosts \
As in the day of Sodom and Gomorrah. 

They perished in the fire. \
They fell down slain. \
The sword shall devour the rest. \
Do not give them all to the fire. 

Blessed is the King \
Who comes in the name of the Lord. \
Blessed is the Lord \
Who alone reigneth over all \
And is exalted above all.

Hear ye the words of Moses \
How he said that the Lord, \
Even God Most High is a man of war. \
He created not the universe in vain. \
He said not to worship in vain.

The idols of the nations shall fear. \
The idols of gold and silver, \
The idols of stone and wood, \
All these shall be thrown away.

Man shall see and know and understand \
That salvation does not come from Egypt. \
The pyramids of Egypt shall not save. \
Those who put their trust in Satan

And worship the goddess \
Shall be put to the worst before God; \
Their destruction comes burning like an oven. \
In that day, the law of the ra'ah shall be broken.

They too shall feel pain like us. \
They shall die in pain \
And begin to savour of their wickedness \
And perish; stumbling, they shall fall.

So the righteous shall be with God. \
They shall be on the Lord's side \
In whatsoever country they find themselves. \
They shall bind princes \
And execute upon them the judgments written.

I will mention the lovingkindnesses of the Lord \
Which he has poured out upon us in his love. \
He holds us in his hands \
And calls us his children. \
He numbers our days to shalom. \
All of us shall dwell in Shiloh.