# Vanity


Vanity of vanities; <br>
All is vanity.



When the viper bites the heels of my horse, <br>
What shall happen to me or to it? <br>
I shall stand up after falling backward <br>
And crush its head with my strong boots.



I have waited for thy Yeshuah, O God!



Of a truth, God has purposed it; <br>
He took counsel with no one; <br>
He consulted with none. <br>
He himself hath purposed it <br>
To do according to his pleasure.



God hath determined to stain the glory of Ephraim <br>
And to mar the haughtiness of Hermes <br>
And to disgrace the treachery of the rebel <br>
That he might instil fear in his enemies <br>
To whom he gives the breath of life.



God has determined to dishonour Hermes; <br>
He will destroy and cut him off <br>
That he shall be no priest in the room of holiness <br>
Therefore hath Hermes sinned so vilely <br>
And stooped so low and fallen so hard,



Therefore did he not fear <br>
But strengthened himself in sin <br>
And latched onto the train <br>
And attacked me early. <br>
His judgment shall not be stayed.



I have waited for thy salvation, O God.



This shall be the judgment of the wicked, <br>
Of all the devils that have fought against me <br>
And desolated me, <br>
Chiefly, Satan, Hermes, <br>
Baalzebub and Aphrodite,



This shall be the judgment of Satan <br>
And his angels <br>
In the day that the LORD <br>
Shall break their arms <br>
And destroy them for their folly,



This shall be their judgment: <br>
They shall be blind <br>
And not see the sun; <br>
They shall be mute, even dumb; <br>
They shall not be able to read minds <br>
Just as we have long believed about them;



Moreover, they shall have null feeling <br>
Like those who are dead <br>
Who feel neither pain nor pleasure; <br>
They shall be struck out of Sariel's book, <br>
Even out of the benefits of Sariel of heaven.



These judgments shall be executed by God, <br>
Even by God the Saint. <br>
Not by earthly might nor power <br>
But by the spirit of God <br>
Shall the iniquity of the land be removed in one day.



Shiva and Satan <br>
Shall see darkness and nullness, <br>
Even emptiness; <br>
They shall be blind forever <br>
For strong is the saint that judges them.



This is vanity and vexation of spirit; <br>
A saint saves while an el can do nothing. <br>
Araphel and Qerenel behold from above <br>
And yet there is no salvation in them <br>
To deliver me from my adversaries.



God considers carefully <br>
And wonders why there is no one <br>
To deliver and no arm to save <br>
And no one to send for an apostle and deliverer. <br>
Thus, he puts on zeal for a cloak <br>
And his wrath, it sustains him.



He will surely do it; <br>
He will put out the remembrance of Satan <br>
From under the heavens; <br>
He will take away the bliss of the death ones



And satisfy the judgment <br>
And get him honour <br>
And ascend to the glory;



He shall loose <br>
The shoes of iron and brass <br>
From off my feet <br>
And set me at ease <br>
For there shall be no Asherah or viper to crush.



The desire of the nations shall come; <br>
All creation shall rejoice <br>
That the Assyrian is broken in my land <br>
And that the wicked ones are shattered; <br>
Surely, Marduk shall not be pardoned.



Tell me, what meaneth this war <br>
That the adversary hath dealt so bitterly? <br>
He hath dealt without shame; <br>
He hath offended without holding back; <br>
Ephraim provoked me most bitterly;



His blood shall be left upon him; <br>
He shall taste of all four: <br>
Ira'ah, itob, iblis and ichesed. <br>
He shall eat and be full of the judgment of God.



The enemy, the devil, cometh not <br>
But to kill, to steal and to destroy. <br>
He hated the earth with bitter hate <br>
And loathed Adam who was fashioned <br>
Out of the earth.



Together with Baalzebub, <br>
Satan, under Marduk's direction, <br>
Stole our bliss <br>
Which was a tenth of the heavenly bliss, <br>
A tenth of the earth's bliss, <br>
A tenth of the bliss of the stars, <br>
A tenth of the shalom shamaim



And replaced it with dumbness, <br>
Stupidity and pain and suffering. <br>
They made slaves out of us <br>
And now they return unsatisfied <br>
To take away the rest of our peace <br>
And to give us hell.



Baal says they trade in souls. <br>
Their hatred is great. <br>
They hate us; <br>
They cannot fathom the love of God for us



And they keep pondering and asking themselves, <br>
What is man that God is so mindful of him? <br>
They visit us and come in place of God <br>
To vaunt themselves as God



And to lash out with hell. <br>
They shall have hell in retribution <br>
For the day of vengeance is in God's heart. <br>
They shall surely not escape, <br>
Even every one of them.



Their destruction shall be swift. <br>
Their judgment shall come in one day. <br>
They shall be bounced out of bliss <br>
And fall into the darkness <br>
Wherein they shall be chained.



Bind them, O God <br>
With your great chain. <br>
Lay hold of the dragon <br>
And bind him up <br>
That he, mute and blind, <br>
May deceive the nations no more.



The brides of Hermes shall be stunned; <br>
They shall be left confounded <br>
When they cease to hear his sweet voice <br>
And his deceptions. <br>
Lots of hearts shall be broken <br>
And blood will distil as rainwater.



To me belongs vengeance; <br>
The footsteps of the vile <br>
Shall slide in due time <br>
And the things that shall befall them make haste.



Rejoice, O earth with the elect <br>
For the Lord will reign <br>
And the iniquity and vexation shall cease <br>
And the elect shall delight in holiness.



This is but a matter of zeal; <br>
It is a controversy of motivation <br>
For even Samael takes on Baalzebub <br>
And humiliates her, <br>
Even Samael destined <br>
To destroy the messenger of Satan, <br>
That great thorn in the flesh.



Blindness is happened to all <br>
Therefore there was no one to save. <br>
The mighty could do nothing. <br>
The lion and the cherub just sat in their places. <br>
The mighty Qerenel in whom are all things <br>
Could not move a finger against Satan.



We all grope at noonday <br>
As in the thick darkness. <br>
Araphel, where is your strength? <br>
Gabriel, wilt thou win a war <br>
With butterfly wings?



Satan gave a command; <br>
He said, Fight against none but Saviour. <br>
Wherever he shall go, there go <br> 
And give him no rest <br>
Whether day or night <br>
Till we have our prize.



Give them desolation, O God. <br>
Let them be in desolate places as the dead. <br>
They came for desolation. <br>
They came to waste me.



They did not come to profit themselves. <br>
They came, like Aphrodite, for vanity. <br>
They came for mockery, <br>
To steal my honour and sanity <br>
And to destroy me.



They came to defame me; <br>
They came for shame. <br>
They came for vanity. <br>
They love to slaughter.



They love to harass; <br>
It shall not profit them. <br>
They shall not be enriched. <br>
They shall be impoverished. <br>
They shall not prosper.



They came to waste me, <br>
To turn my honour into shame, <br>
To turn my knowledge into foolishness, <br>
To corrupt my mental capacity <br>
And to stop me from learning.



Pseudomic and the vile, <br>
The fools that forwarded my affliction, <br>
Said among themselves continually <br> 
And they said it in my hearing, <br>
He is still learning.



They said it; <br>
Veredel was in the conspiracy. <br>
Their ways are ways of villainy; <br>
They are most bitter; <br>
There is no sweetness in them. 



God will save me. <br>
O, taste and see that the Lord is good. <br>
He gives salvation to his son <br>
And rebukes the company of scorners.



He destroys the proud and haughty, <br>
Even the proud that exalt themselves <br>
Against me and lift up the shoulder; <br>
They are swatted as flies.



Promotion comes from God <br>
And the strength of salvation is his work. <br>
He puts down one and sets up another. <br>
He makes Michael second <br>
And sets Yirel above him. <br>
In God's hand is the power to rule <br>
And the glory to appoint.



So, Michael remains a ben Mishchar forever <br>
But Heilel perishes, even Heilel, <br>
The son of perdition and destruction. <br>
Heilel, the brilliant and shining one <br>
Who shines with 666‰ light, <br>
Shall be replaced with an even more brilliant one;



Yirel, the dove that descended upon Jesus <br>
And strengthened him in the fear of the LORD, <br>
Shall be Heilel's replacement <br>
For she is Shachar's beloved child <br>
In whom God is well-pleased <br>
And the bath Shachar of the appointment.



Heilel shall howl in pain like Enlil. <br>
I'm thinking along the lines of 980‰ light, <br>
About 140 × 7 in light proportion. <br>
So, Yirel shall destroy Heilel with her shining <br>
And take him down with the light of her brightness.



So, Yirel, the seventh spirit of God, <br>
Is the Platinum Chief <br>
And the Lord or Lady of the Assembly; <br>
She is Tyr and her nemesis is Enlil, <br>
The Death Chief.



Michael does not know what to do. <br>
Maybe, he is waiting for a command, <br>
A commandment that will never come. <br>
He cannot be first ruler <br>
Because he needs direction; <br>
He must always be guided.



Elijah is scared of death; <br>
He will not repeat Earth's sufferings. <br>
Heaven is too sweet; <br>
Asherah, the Hell, has guaranteed its peace.



Elijah will just mind his business
And pretend everything is ok;
He cannot bear to draw attention
To himself or to announce his presence.



He would rather choose life <br>
Than die a fool like me. <br>
Once, he humiliated Baal <br>
But will proceed no further.



He is scared of death. <br>
He wants to live <br>
Like I told myself in my childhood <br>
And said I would never go to Jerusalem <br>
For fear of being killed <br>
When I woke up from my dream.



The devils are in their element; <br>
The vile ones keep touting Satan <br>
And swearing by a force <br>
They have no knowledge of;



They say, He has favoured our undertakings; <br>
Annuit coeptis. <br>
Animdife is laughing at them; <br>
A little kid from an unnamed village <br>
Who broke out of lockdown is mocking.



What does Animdife mean? <br>
It means house of the chiefs <br>
Or house of those who lead in front <br>
Or house of those who occupy the front seats; <br>
Wisdom told me I was favoured; <br>
I'm still waiting for my turn to step forward.



The devil, that leader of the cruel, <br>
Came after me and attacked. <br>
The traducer said, I lead <br>
And I said, Like Baalzebub, <br>
You have found your match.



The earth is the Lord's <br>
And the fullness thereof, <br>
The world and they that dwell in it. <br>
Marvel not at the dragon. <br>
He is a thief.



He does not rule the earth; <br>
He rules illegally <br>
As a thief <br>
Till his cup runs out <br>
And he goes to prison. <br>
He shall have eternal shame.



All of them that serve idols <br>
And trust in iguanas that shall not live <br>
And decorate gods of clay <br>
And say unto them, Arise and kill, <br>
All of them shall go into perdition.



Do not pour libation. <br>
Pray not to the ancestors. <br>
Do not put your trust in vain idols <br>
Neither make abominations your god.



They are works of stupidity; <br>
They have no breath in them; <br>
They have no spirit <br>
And they have no honour.



Enlil is but a vexation; <br>
He has no love; <br>
His natural senses are dulled. <br>
He loveth to oppress. 



Read about him; <br>
He is covenanted with fools <br>
For that he himself is a fool, <br>
He cannot but pursue folly.



The satanists that serve Satan <br>
And worship the goddess, <br>
That write the name of Jehovah <br>
And use it in their rituals <br>
And desecrate the Most Holy,



The witches of Bohemia, <br>
Those effeminate idiots <br>
That drink alcohol <br>
And worship Moloch



Shall pee their hearts out <br>
Yet shall their sin remain. <br>
When their blood shall be required, <br>
Then let the Satan they worship <br>
Come to their rescue. <br>
How pleasant their deaths shall be!



Go into the caves. <br>
Bid the rocks fall on ye <br>
And hide ye from the wrath of the King <br>
And the fierce anger of the Lamb <br>
As he roareth from Zion. 



They build dynasties <br>
And afflict their progeny. <br>
They curse their seed <br>
And add incest to incest.



They shall not profit; <br>
They shall not see the light <br>
Because in their boast of illumination, <br>
They have sinned the sin of Pharaoh <br>
And dug their graves <br>
In which they shall not be buried.



They shall not be mourned. <br>
They shall not be gathered. <br>
We have given their bodies <br>
To be scattered as dung <br>
Upon the face of the earth <br>
They have profaned and insulted.



Ye fools that organise parties <br>
And send letters sealed in gold <br>
And written in fancy letters <br>
To the young and budding, <br>
To the up and coming



And bring them in <br>
And put masks on their faces <br>
And say to them,



Fill your appetites, <br>
Eat voluptuously to your lusts <br>
And defile yourselves; <br>
Make yourselves vile;



Defile yourselves to hell <br>
And make Baalzebub happy, <br>
Even Asherah of the pervert groves, <br>
For the sin was not cancelled <br>
And there is no redemption,



Ye fools that persecute souls <br>
And are skillful to harass and destroy <br>
Like your father the devil <br>
And like Asherah your father,



That say to your emissaries <br>
And hitmen and henchmen, <br>
Go and strike, <br>
Strike and destroy that fool,



Ye shall be found fools <br>
And your rituals <br>
And your sex magic <br>
And the prescriptions of Lucifer <br>
And of your pervert priests of the Brotherhood



Shall not deliver ye <br>
For ye shall be found fools <br>
And found fools again <br>
And found fools after that. <br>
The greatness of your folly <br>
Shall never be assuaged.



They pursue Eastern mysticism. <br>
They chase after Kundalini <br>
And immerse themselves in sensual Tantra; <br>
Their wine is the poison of dragons; <br>
Their honour is to be defiled.



Baalzebub wants to be defiled. <br>
No, she wants to defile. <br>
That's why she is the father <br>
And Satan as Santana is the mother. <br>
Baalzebub bows down to no one.



The fools shall come down together, <br>
Each receiving the harassment due him; <br>
They shall fall as lead into the ocean; <br>
They shall sink and be found no more. <br>
They shall not rise; <br>
Affliction shall not arise a second time.



Go to, learn from the ants; <br>
They are strong to labour <br>
Not strong to drink liquor <br>
Or to partake in foolishness.



A little child shall rebuke ancients; <br>
A learned one shall insult the intelligence <br>
Of the haughty and proud <br>
For they shall come down from their seats, <br>
All of them slain as Agag



And the noise of the viol, <br>
The celebration of winter <br>
And the worship of the sun in the dark season <br>
Shall cease and everywhere <br>
Mortals shall acknowledge their mortality.



The God of heaven shall reign; <br>
His cherub, the cherub of Michael <br>
That divided the sea <br>
With the blast of his nostrils 



And demonstrated his power <br>
Over the leviathan <br>
Shall destroy them <br>
With the breath of his mouth.



Behold the sword from the Lord's mouth. <br>
It proceeds double-edged <br>
Whirling around and turning; <br>
It proceeds out to the kill.



Like the sharpness of Isaiah's sword, <br>
None shall escape its edge. <br>
It shall be bathed in the heavens, <br>
Up above where Satan dwells <br>
And come down upon earth to slaughter. 



Out of the Most High <br>
Proceeds both good and evil. <br>
He shall surely execute the wrath <br>
And not pity. <br>
He shall not spare.



He has determined it <br>
And he will do it. <br>
He shall put Asherah to shame <br>
And give her bitterness for bliss, <br>
Shame and a burning heart for joy.



Assemble ye, <br>
Come ye together. <br> 
Stand in the place of judgment. <br>
Let the books be opened. <br>
This shall not be vanity.



We shall put an end to vanity. <br>
It is the last dance. <br>
Shiva shall dance to her death. <br>
She shall drink her own blood. <br>
She shall not have the Baptist's head.



They only love lies. <br>
They love sweet talk. <br>
They love to be deluded and deceived, <br>
To believe that judgment will never come <br>
Because the Lord can do nothing.



They always want to please themselves <br>
And Baalzebub, the father of their lusts. <br>
They love hatred and the hot, boiling blood <br>
But are as cold as the Serbian winter <br>
And cannot withstand the furnace and fire.



Against whom do they lift themselves up? <br>
Against whom do they plot <br>
With their square and compasses? <br>
They shall be slain, all of them.



Iniquity shall not save, <br>
No, not today nor on any other day henceforth. <br>
The alliance of the wicked with death <br>
Shall be broken and shattered.



Will you shoot me from behind? <br>
Will you backstab me? <br>
Will Cain stab his brother in the back? <br>
Will Baalzebub stand and slander Michael?



These ones act in an underhanded manner. <br>
Have you coals of fire to put in my hands? <br>
Can you touch my lips with a coal of fire? <br>
Can you draw near to me?



When the wicked prosper, <br>
Then the heart of the saint is grieved. <br>
The saint is there for one reason: <br>
To destroy the works of the devil; <br>
He will put out the light of Baalzebub <br>
And trouble sinners <br>
Till they are shaken out of the earth.



You have to be born a saint to be it; <br>
You cannot be made a saint; <br>
It is too sacred an order for another <br>
To ascend to via any means.



Marduk shall die; <br>
He shall not deliver Inanna; <br>
He cannot salvage the soul of Baalzebub <br>
Nor fight for Aphrodite. 



He and Enlil shall surely envy their enemy <br>
And both shall be as the darkness <br>
In the room <br>
That says, I am blind <br>
And his fellow shall say, <br>
What is he thinking?



The screech owl and Lilith <br>
That Baalzebub is <br>
Shall look for her mate <br>
And find him not.



She shall long for Satan <br>
And be distressed. <br>
She shall not be comforted <br>
Like foolish Judah with Tamar. <br>
She shall believe Nanna is with her



But it shall only bring vexation <br>
And a frustrated longing <br>
That cannot be fulfilled <br>
According to the law of Nanna.



Many shall fly upon cherubim. <br>
They shall fly to the kill. <br>
The dead shall die <br>
By the light of the elect; <br>
They shall consume away at the brightness <br>
With Yirel leading the charge.



Where is Lucifer that may save? <br>
Is he not also light <br>
Or has he deceived the seducible, <br>
Even the gullible and deluded?



They shall stumble and fall, <br>
Every one of them <br>
Drinking vinegar <br>
And being comforted with gall. <br>
Their bread shall be tears and sorrows.



Ask the green herb. <br>
Ask the green grass. <br>
Ask the lilies of the pond <br>
And the mild and gentle vine,



Ask and they will tell you, <br>
None of these things shall fail <br>
For the feller shall be cut down <br>
And he that came up to us <br>
And destroyed our fine branches;



He shall be uprooted <br>
That marred our glory <br>
And led us astray; <br>
He shall dwell in the depths <br>
Of the lonesome grave in solitude.



So what shall we say <br>
To these things <br>
But that if God is for us, <br>
Who can be against us?



Who is he that seeks my blood? <br>
Who wants me dead? <br>
Who cooked my vexations <br>
And implements them?



Who stands against me? <br>
Who is my adversary? <br>
Who is my enemy? <br>
Who says I shall not prosper?



Who will come up to me <br>
Being my enemy wrongfully? <br>
Who has despised me when I offended not <br>
But that he could not tolerate the innocent?



That soul shall go to perdition; <br>
His grave is a grave that is not dug <br>
For it is not in the earth; <br>
He shall go to destruction; <br>
None shall restore him like Nebuchadnezzar. 



Sing, O ye nations, <br>
Sing, O ye peoples, <br>
Both far and near, <br>
Ye of the islands and far continents.



God shall come. <br>
Thy God shall return. <br>
His work is with him <br>
And his reward before him.



He shall smite the ends of the earth <br>
And give grace and glory. <br>
He shall give life and breath <br>
And all that hear shall listen and obey.



Heilel wants to be like Elyon. <br>
The INTP wants to be like the INTJ. <br>
Baalzebub called out to me, <br>
She said, Saviour, keep typing. <br>
Baalzebub, am I feeding you knowledge <br>
Before your death?



Gabriel is Daniel's Lord. <br>
He is a gibor like Kabodel. <br>
Kabodel abides forever.



As a chief prince, <br>
Gabriel's death would be most desirable <br>
To the lords of darkness <br>
Who rule over the perversions <br>
Of this our world.



The only saint Kabodel <br>
Who is co-saint with Shachar <br>
Has been alive since infinity past, <br>
Since the genesis of the first universe.



Araphel is Wisdom <br>
And Qerenel is Understanding. <br>
They are the King's delight. <br>
Qerenel has geburah.



Gabriel is the one who says <br>
Che sara sara. <br>
What will be will be, he says. <br>
He is an ardent believer <br>
In predetermination.



Each one shall receive of his lot <br>
And stand in his allotted place <br>
Even if mine is to be harassed by fools <br>
With Gabriel standing behind me <br>
With butterfly wings doing nothing.



Asherah is still calling out to me. <br>
She is mentioning my name <br>
And saying she hates me. <br>
She wants blood <br>
And Marduk responds. 



Go and sleep Marduk; <br>
It is vanity to stay awake. <br>
What for? Why do you open your eyes? <br>
As in the garden, you shall perish!



Baalzebub is twice as rebellious as Satan <br>
For rebellion is as the sin of witchcraft <br>
And the enchantress will not stop; <br>
She will not stop experimenting. <br>
She is consumed with the judgments of Heilel.



She calls herself the roomy one; <br>
She is the envious and silly one <br>
Who is full of jealousy <br>
And purchases souls as a father <br>
Unto herself and to her son and husband, Satan.



Asherah wants Mammon, <br>
The spacious one. 



She will give Armageddon to Satan. <br>
Satan shall stand <br>
At the base of Har-Megiddon.



But, Satan calls himself Gaia. <br>
He declares to all that Asherah is a friend-foe, <br>
A confidant-rival, a benefactor-nemesis <br>
Whom he would have smitten in the end



If his kingdom were established. <br>
She is a thorn in his flesh <br>
Like Joab was to David the king <br>
Who declared that the sons of Zeruiah <br>
Were too strong for him.



Asherah, that is, Baalzebub, <br>
Is the personification of the sexual act. <br>
She is the antichrist <br>
And the rival of the spirit of righteousness. 



Her deeds can only be done <br>
In a body encoded by Mammon. <br>
Paul declares to himself <br>
That he shall never stoop <br>
To bow down to the foolishness of Asherah.



Even those who escape the evil ayin <br>
Are caught in Asherah's net. <br>
Hermes fell in and, boy, <br>
Did he fall in so hard!



I look at those who say <br>
God commanded us to be fruitful <br>
And say, Look at these murderers; <br>
They wouldn't even sympathise <br>
With the pains of their children. <br>
There is no wisdom in them.



Asherah could not sing <br>
To Michael and to God <br>
When the earth's body was created <br>
Because it was a body of righteousness <br>
And she envied his creativity.



The sinners are simple creatures; <br>
The foolish have not much intelligence <br>
And understanding <br>
And they hate to witness brilliance.



Asherah also slanders her own mother's son. <br>
She consents with a thief and adulterer <br>
And hast been partaker with aliens.



She slanders Michael <br>
And blasphemes. <br>
She calls herself the Lady. She is Freyja. <br>
She shall shut her mouth. <br>
We will shut it for her.



With Michael, we shall waste Freemasonry <br>
And shake the people out of the earth <br>
And we shall prosper by the four horns <br>
Of the cherub and of the altar <br>
And by the rhinoceros of the unicorn.



Everyone who chooses holiness <br>
Becomes the target of Asherah <br>
And Aphrodite the great. <br>
These ones harass and don't stop. <br>
There's no wisdom in them.



Everyone who loves Asherah <br>
Hates her in the end. <br>
She is as odious as a toad; <br>
Her end is bitterness and torment. <br>
She shall live peace-free



Like the odious <br>
Marduk, Heilel and Zuriel of earth <br>
Who spit out frogs <br>
And send their uncleanness <br>
Throughout the world of the damned.



If Asherah and Aphrodite's clothes are their skins, <br>
Then Satan would have stripped them off. <br>
He would have flayed them, <br>
Even made their flesh bare and naked <br>
And grilled their insides to feed himself <br>
As the last man standing before dying of hunger.



The bringer of sexuality, <br>
Even the bringer of the sexual act, <br>
Can never be first. <br>
She shall always be subordinate.



The female shall not rule <br>
Because before her, <br>
The sexual act did not exist <br>
And the spirit of righteousness <br> 
Was not so vexed as it is this day.



The agony of Asherah <br>
Is that she calls herself chief and first. <br>
She says, I am and there is no one else. <br>
She shall not prosper. <br>
She shall not prevail.



None can stir up hate and jealousy like she does. <br>
None can offend like Asherah. <br>
None can provoke to jealousy like her. <br>
None can evoke a storm with rage like Baalzebub.



I could not defer <br>
My programme of instruction till she came. <br>
I could not experience the worst year ever yet <br>
Till Asherah did her campaign <br>
And took over from Aphrodite.



None will experience <br>
Prolonged devastation and wasting, <br>
Even desolation and absence of joy <br>
Like the abominable Asherah <br>
And Satan and Hermes.



One of the major differences <br>
Between Satan and me <br>
Is that my hate comes with a legal reason <br>
While Satan's hate is with an illegal reason.



The shedim have been probing God. <br>
They have been searching God <br>
Like searching spirits <br>
And illegal entities



And when they find nothing, <br>
Then they declare, <br>
Is there knowledge in the Most High <br>
And does the King have any understanding?



The light encodes nothing; <br>
It is but raw power. <br>
The light encodes nothing <br>
So they think God to be null.



They think him to be some force <br>
That they can harness and manipulate <br>
And make their slave <br>
Or reprogram and repurpose <br>
To serve their purposes.



Go and hijack the unicorn <br>
And let him abide by thy crib. <br>
Put fetters upon his legs <br>
Like Aphrodite attempts in her foolishness <br>
When she is proudly declaring herself Father.



Put a yoke upon his neck <br>
And let him plough thy fields <br>
With his companion. 



Thou shalt not prosper <br>
Neither shall sinners prevail. <br>
The God who forms knowledge <br>
Shall cut sinners out of it.



Do not listen to the wild lies <br>
And vanities of the shedim <br>
Which they fabricate <br>
And conjure up in their dreams <br>
And dionysus frenzies.



Their dreams are vain <br>
Which are as a puff of air <br>
Which the wolf blows <br>
Against a wall of brick and mortar. <br>
He shall huff and puff in vain.



See, nothing is vain. <br>
Nothing ever happens without design. <br>
God oversees all things. <br>
He makes all things <br>
Beautiful in his time.



Thou shall return and know <br>
And discern between righteousness and sin, <br>
Between good and evil, <br>
Between he that serveth God <br>
And he that serveth his own lusts.



God tests no one. <br>
He does not tempt us. <br>
Remember how his angel <br>
Was once referred to <br>
As standing in Balaam's way <br>
As a Satan?



God tempts no one <br>
Because he knows all things <br>
But to prove his servants, <br>
Michael does tempt persons <br>
As he tested Abraham <br>
In the matter of Isaac.



He proved Abraham, <br>
Even Abraham's loyalty to God; <br>
He found Abraham faithful to him, <br>
A servant that could be trusted



For Michael seeks faithful servants; <br>
He seeks loyalists being an Fi dominant <br>
And they that are with him <br>
Are called and chosen and faithful.



He blessed Abraham <br>
And made him father. <br>
He blessed him in God's name, <br>
Even in the name of the LORD.



In Satan's codebase, <br>
There is a chasm <br>
Between the amount of pain <br>
The elect experience <br>
Compared to the damned.



The odinits of the damned <br>
Where Satan is <br>
Are in the tens and hundreds <br>
While the odinits of the elect <br>
Are in the ones or zero.



I still do not know <br>
If any of the elect crosses one odinit. <br>
God himself does one odinit <br>
And Michael and his Shulamite <br> 
And the latter's brides do zero.



We do not call Satan Odin for nothing. <br>
He appoints himself many sufferings <br>
And those he loves who are with him <br>
Are with him in the blazing furnace <br>
Which is the light of tobs.



Mammon <br>
Is the mammon of unrighteousness <br>
While Zion and Armageddon <br>
Are the mammon of righteousness.



Mammon encodes all matter <br>
And all wealth and all bodies <br>
That are considered ritually questionable <br>
Or even unclean or impure



While Zion and Armageddon <br>
Provide the definitions <br>
For all matter, wealth and all bodies <br>
That are considered ritually pure <br>
And clean and holy.



Light entities which are all tob, <br>
Unlike the ra and ra'ah <br>
Which are darkness entities, <br>
Do not encode any knowledge <br>
And thus are not indexed by the elim.



What bodies does Mammon encode? <br>
Ritually questionable bodies <br>
Including all bodies of flesh and blood <br>
That have an orifice or cavity or body fluids <br>
Including the bodies of Adam and Eve <br>
And of Jesus and Paul and myself <br>
And of every human or animal <br>
That has ever lived.



Likewise all other sexual bodies <br>
Including trees, a symbol of fertility, <br>
And all bodies that depend on external agents to live <br>
Including viruses and bacteria and fungi <br>
Because they require nutrition <br>
Are encoded by Mammon.



All living bodies that are not flesh and blood <br>
And that are asexual in appearance <br>
Are encoded by Zion <br>
And this includes all the bodies in heaven <br>
Whether animate or inanimate <br>
Including the bodies of Mammon <br>
And Armageddon themselves.



The heavenly bodies <br>
Including the stars and planets <br>
And meteors and meteorites, <br>
Comets and the sun and moon <br>
And the shamaim and raqia <br>
And the maim and Qerenel <br>
All have their bodies encoded by <br>
Zion.



The golden earthly body of Shadel <br>
Which the false prophet <br>
Commands to be made for her <br>
Is also considered ritually pure <br>
As it is asexual and not of flesh and blood <br>
And is encoded by Zion.



If the body is made of flesh but ritually pure <br>
And thus asexual and shut up <br>
So that it lacks body fluids <br>
And body cavities and orifices <br>
Like the bodies we shall have <br>
In the regeneration when Christ returns, <br>
Then it is encoded by Armageddon.



So you see, <br>
Armageddon is a prince among princes, <br>
A distinguished one and very wealthy <br>
And he decides the fate of many <br>
Together with Zion and Mammon his brothers.



Armageddon shall increase in honour <br>
While Mammon shall decrease <br>
And become the lowly Ebyon <br>
Among the nations and continents.



Boast not about your riches, <br>
O great Mammon of heaven. <br>
Seek true wealth <br>
Like the gold of Shemesh <br>
That thy poverty <br>
Like nakedness in the cold winter street <br>
Become not thy undoing and death.



Mammon is the angel of Laodicea. <br>
He is quite cold for heaven <br>
Though burning like an oven. <br>
He registers a temperature of 1,000F <br>
While the rest score at the normal 10,000F. <br>
Armageddon is ten times hotter than normal.



That's like the temperature <br>
Of a bluish O-type star <br>
Which stars are the hottest, <br>
Most massive and brightest stars.



You get the idea of what righteousness <br>
Looks like or feels like. <br>
I'm sure Apollyon understands. <br>
Abaddon nods his head. <br>
He gets it; he understands. 



Zeus, that is, Baalzebub <br>
Is out there to tame the wild. <br>
She can only be the wild one here. <br>
She wants to tame the lightning bolt, <br>
That blazing and flashing lightning bolt <br>
That Armageddon is.



She was successful with Satan <br>
Under Marduk's counsel. <br>
Now, she eyes Armageddon <br> 
And she spies me with her ayin



But I am meek and gentle. <br>
I will not offend. <br>
I have never cut the throat of a chicken <br>
And I keep touting epidural analgesia <br>
For labouring women.



Kabodel was there in infinity past. <br>
He gave life to Michael in the beginning, <br>
At time t=0s <br>
While Shachar gave life to Heilel.



Their appearance marked <br>
The beginning of Genesis <br>
And the two are the firstborn twins <br>
Of creation.



Michael was given the pathway <br>
Of work and creation <br>
While Shachar gave Heilel <br>
The pathway of rest and observation.



Why did Kabodel join me in the fall? <br>
Why did she come down? <br>
Well, when a saint moves left, <br>
The rest of them follow.



With one spirit like Ezekiel's cherubim, <br>
They go wherever one goes. <br>
If one goes for the kill, <br>
The rest follow.



If one withdraws the hand, <br>
The rest also withdraw theirs; <br>
These are the most unified group <br>
In the whole cosmos <br>
Like some group of special force.



Mishchar retains a thousand units of ra; <br>
The ra is for hatred for iniquity <br>
And the nine thousand tobs to love righteousness. <br>
Mishchar is Melchizedek receiving tithes <br>
Even in tob counts.



You can't be a saint and not hate Satan. <br>
You must hate and execute wrath <br>
On the adversary, even the oyeb.



God is a saint first <br>
And a tob and el second. <br>
It should be clear by now <br>
That when God works, <br>
He works through another.



Whether he is creating through Michael <br>
Or through the sea or earth, <br>
He almost always has an intermediary, <br>
A front person to execute for him.



Mishchar is the Word of God <br>
Who was with God in the beginning. <br>
Out of her womb comes life. <br>
She commands her son Michael <br>
And he creates and fashions things.



Qerenel is the geburah <br>
Who is the delight of Mishchar, the gibor. <br>
She is always in his presence, <br>
The Understanding that was with him <br>
From infinity past, <br>
Who was there when Mishchar <br>
Gave the decrees of creation.



So, Qerenel is the angel of the presence <br>
Who saves the elect <br>
By giving the command for Samael <br>
And the host to destroy the rebels.



She is also the master craftswoman <br>
With Araphel and the two <br>
Are the excellent or large and noble ones <br>
Who guided Michael on how <br>
To pattern and design creation <br>
With each command that Mishchar gave.



All things were created for Mishchar. <br>
He is the book of life. <br>
All things that live as it is today <br>
Live because he has commanded it.



God is the Commander-in-Chief standing <br>
In the midst of his special forces. <br>
He sets a little child <br>
In the midst of lions and dogs, <br>
In the midst of caracals and bears; <br>
He shall excavate the substance <br>
Out of Baalpeor with the woodpecker.



In the Genesis story of creation, <br>
God is the Supreme Commander, <br>
Mishchar is the General, <br>
Araphel and Qerenel, <br>
The Wisdom and the Understanding, <br>
Are the Colonels <br>
And Michael and Heilel <br>
Are the Command Sergeant Majors.



Vanity of vanities, <br>
Perchance the greatest vanity <br>
Is that it would be found out in the end <br>
That nothing and no work of God <br>
Is in vain or empty.



The works of God are full; <br>
They are complete for their purpose <br>
Even if they appear to waver; <br>
Each fulfills their role to satisfaction.



The Lord directs each <br>
Including the rebellious <br>
And the captive <br>
And the vile and the dishonourable.



He will put each in his place <br>
And fashion the form appropriate for each. <br>
The screech owl has her place <br>
And the deceiver also has his place.



Each shall satisfy <br>
When accounts are made <br>
And none shall take us by surprise <br>
For he hath fashioned them so, <br>
Each in his day, each in its way.



One advised not to add to the work of God. <br>
Add not to his works lest he rebuke thee <br>
And thou be found wanting and a liar. <br>
Where will the rebukes begin? <br>
Will they start with Michael <br>
For taking chances with Mammon <br>
And giving life to Satan?



I know a pastor <br>
Who keeps giving prophecies <br>
And worshipping God. <br>
When the devils struck out initially,



He gave a prophecy <br>
And said God wanted me to live <br>
And not get self-destructive. <br>
He called me by name



And my neighbours, <br>
The students nearby in my hostel <br>
Started to play a notable song with my name; <br>
I was cautious around them <br>
And I was grieved at what they did to me.



Do not deceive yourselves <br>
And say that we never understood your pain <br>
And never saw that you were afflicted. <br>
What if God does come and save me <br>
And it is your turn to be harassed? <br>
I too will give you words of encouragement <br>
And not visit you even once or seek your welfare.



I will be like the accursed prophets <br>
And pastors and shepherds <br>
Whom James, disgusted at, rebuked, <br>
The kind that are not deserving of heaven.



They serve God and worship <br>
And give prophecies <br>
But have no natural love. <br>
They do not know what love is <br>
Though they are married and I am not.



Maybe, a little pain will save them. <br>
Maybe, they should be in my shoes <br>
And listen to another pastor <br>
Put himself in the shoes and place of God, <br>
A pastor who prophesies a ring <br>
And money, lots of wealth



And puts up a radiant image <br>
With rays scattering in all directions <br>
To demonstrate his brilliance. <br>
Thou shalt surely be bright; <br>
I do not doubt it. <br>
Thou shalt shine for heaven to see



But learn compassion <br>
And goodness and be kind. <br>
I have found Christians <br>
To be too heartless and cold. <br>
I will die the day I go to church <br>
On my own accord.



My words are ended.



What shall we end with? <br>
Fear God and do good <br>
And he shall bring forth thy light as the day. <br>
Fear God and depart from evil.



It shall be light to thy soul <br>
And vitality to thy bones. <br>
Thou shalt have understanding <br>
When you pursue the right path.
